apiVersion: v1
kind: Service
metadata:
  name: matrix
  namespace: apps
spec:
  selector:
    app: matrix
  ports:
    - name: http
      port: 6167
      targetPort: 6167
---
apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: apps
spec:
  selector:
    app: matrix
  ports:
    - name: http
      port: 3478
      targetPort: 3478
