apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nelsondane-wildcard
  namespace: cert-manager
spec:
  secretName: wildcard-cert-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - nelsondane.com
    - "*.nelsondane.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cilium"
