apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - cluster-issuer.yaml
  - gateway.yaml
  - helm-release.yaml
  - helm-repo.yaml
  - namespace.yaml
  - secret.yaml