apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:A6IYNLUkSip/ld4ayU/8R7G9MKG32Vjm3duc6lq8/TCX063NWjwHbg==,iv:0DzC8xRBeKyVPs5o9A91BYN2DPLx5lCnpvU7kNQEJr0=,tag:9SaoNKEjIoaZJaCUpVuibQ==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUWlwck9MV2FwRW9ScG9Y
            eVU4WU90LzFad3VrMkwvMWJPa2x1OTNLOEVVCktuWm1ETkxLWnY5c1d0UHNkbUVK
            VjA0cXdIUEQzdFI0RVl1VU1wTHR2ZDgKLS0tIHNmT2xBN2VNRE5HazBBcFE1Rjdr
            dkV5V2lvdm95YkRMRmFobkdYVUJyM00KcFucAtk67EJtboaYiC4oilc7tB64iZv9
            PpmmnaO+9pb8hHiFLurnnLiozMfss8n7W6V6yOtBrKEaX+NtgRJbXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:12:21Z"
    mac: ENC[AES256_GCM,data:nRr8yaPYjqGyfT/Xt4uXVOFQdgBdN5VU/kNhs8enwwUsxYXyEOllzXRi+NEqeRdkMrLImuIKdv8cWQVFrNRiXrTBuYwff+RysDr3Zl3otVHawMHnRPRivGmLa+Z5N8oIrynlLRH/BDwKDim3GIjgjB9gbAZryNmyWL88kF59DJw=,iv:xv6eKH/6zW6oELmf9LDhHglBQwxJT5tMERtldaWSqkI=,tag:2pbLX+irGNJhVZOhKNYv5A==,type:str]
    pgp:
        - created_at: "2026-01-05T00:12:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAuOP0ymescSaSOTzuyoIm4VE0yHCKcGiD93OwJI546Fsw
            UR5y5Xa5LixEAHowLFBtr9/ljzQwSqzeCUwD9iR55dfCVXcqU9qm+SEzguD2qknx
            1GYBCQIQ+z6QFCJXMBe07pySFWXRQ/fEQ3TXr1Li6ew56PQJaSF5/oTyqtRzpNPO
            +DhdI9Yfd7upd/rpU9AD5IhMfFuuStzh89dtl1EqGVBS6e+/LIbddhBl/VVLNfQ0
            uX5UjhjGzlg=
            =x1j4
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
