apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:OHjiDojU1gO7e5jfT35Wyh/Z4ib/pmVD2sCgvJbfE0OCECC+v/aKjQ==,iv:7XrR3mj39ff6p8/uoaZbBT4JVoCmmMS0kSHiNlESRT0=,tag:cd/mV7ZR957mOe0Yz2dWTg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YThud3pmM2g5cm0zYUU1
            Mndtelc5SVpLQU1HL3p5eDJ5Q2U4WWpXSndVClhjeU9WeDllTER1UkZMZnkvRk5B
            RnJ4VVhpSnB4TmR6ZkxLNGs3MnVkeGcKLS0tIHBxRFZhVEt6cmV1ZzE4MTdJM2Uw
            T09Lc0lScFpndEc1ZjhGY05wc3lWZjAKmHfWXXcuP7i6S8Gkq6327BKdAgw26Ua+
            9DeEf1/ujqhBy+cWiC5fw2OxdhSeOeZIv/6rc+Dh+WZRlQTCKViqWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T18:35:35Z"
    mac: ENC[AES256_GCM,data:vBU3byX8rIZeXPl3vnDhWojn8L/R00BEozmbu/5b3xpFmTZANDWEbHT7MypgP/+dptExv3AfKaU4ICnX5Kcywz2tjg/vd5utsv4NY0SuiIpLqqS6BZUmN/zVGNH3OHsN/Rp8WlfwmeBeo5s9/dLtvBMlZ3F+nSOfRzPwo8qzVe0=,iv:jXh9eNWqf0RdARQr8de6PwDVlSDtdGaBXPMtcsZERE8=,tag:ScdEOBdw1Cah6i2iVceeoA==,type:str]
    pgp:
        - created_at: "2025-11-20T18:35:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAzknyGhobAgoktECh3OQnGP337DAweuufVFUNZO+uFxcw
            lj3s/Qvtzra10gKsy2WYIhApyq7ABc00FlxFjN24TkcE3uDoiD1F0EJtFtWDoaHF
            1GYBCQIQDNiKiDI8lv7vTq+9AgW7ZN2NXEJbF7fSC2ZSoT1FCxa/AfDUpEI31C6+
            AnzIiTgJVMY3J/S16Ek6OMU8b6vSfyN+UTeqC+fjTx85tjLp/LzW4AJJKarFlzLg
            za1MVZaLf3M=
            =2cnR
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
