apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: code.cluster.nelsondane.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code
                port:
                  number: 6901
