apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:AYWdMCU=,iv:J3lyOHMLIaXTD9pCLnaZGjC4QIZcutENFVqdt31Qvfw=,tag:vfK6RpbCd2IwFmojTC9eAw==,type:str]
    admin-password: ENC[AES256_GCM,data:UXcYihm32qbeyuUzrw==,iv:64H7t4CAFenwtwA78y8TOWPT5KyzH2qqRbw7FHXKIL0=,tag:eQTaisfzLXbbVIYJh8vnqA==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ1RjL0hVdnNnNGRFamlm
            cDZqOUtnUU1QOUNwblFvclhLMitLbU5qbWtrCmFtd3dTd1VZK0VEc09NSWg3d2Ew
            ZWp5aVgzTmpUOW9rMHRzcDFvTmNyZzgKLS0tIGw2U3ZjeU4zOGxkeWFzSVdDcU5S
            Rk9vVmpkN0JlSjZJQUVRN255bWc0d28KicKgiorP/TQKO4tdFZXaIEckODwnYFlF
            BiXfUCkYhWNBAitC2FRAsWaSgfxp0uaD7awr4yY51/3Oz2aZcL4BCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T04:56:10Z"
    mac: ENC[AES256_GCM,data:l50uOFNWa36rfBe4ivggZSt0gE9sOFj2dCYIgVx6L1BjVkVp31Yqk2Aig/eOQvMP24tXGR0gd3v4jJDCoBBqJZtoCY6ZShD//dwV0rOHhsGW26nJf++/n3YKdOHHXvlqemuqSvR2uWThQgv2FzUal7TxEnm7rX+8onH/bsTY6LI=,iv:6UxOlM1+a98gV435m/8yOhSiiyhV8436irs0P6HausQ=,tag:afSRrUbtHxdYvmfLsQCvnA==,type:str]
    pgp:
        - created_at: "2025-12-18T04:56:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA/9HNHZHvyTGj2T9cdXCrWJaCRX7Pss3L+5e4icwFtwUw
            Q/8VhmiwJeVgIJU6udADqeTX3SRIFieUbtUaxF/yMJjlKTiwqpCiYDGrpd3F2gq8
            1GgBCQIQ48L9bQ/JBn3QUKjEWqAXVK6Gbvd+3z6dsBzj7oWVLi7SwDFBSoI5hKB6
            ZAnm/D/OEAzCsndHcMpqLVLAoAz5fEBvvmq8XhsShTQZnQhasP5SgWH0oK/OB5Ka
            mOXL5XLcxcm69w==
            =be+5
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
