apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: i915
  namespace: media
spec:
  spec:
    devices:
      requests:
      - name: i915
        deviceClassName: gpu.intel.com
