apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: thelounge
  namespace: apps
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: cilium
  hostnames:
    - thelounge.cluster.nelsondane.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: thelounge
          port: 9000
