apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: capacitor-next
  namespace: flux-system
resources:
  - helm-release.yaml
  - policy.yaml
  - route.yaml
  - repo.yaml
  - secret.yaml
