apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: cilium
  hostnames:
    - next.cluster.nelsondane.com
  rules:
    - backendRefs:
        - kind: Service
          name: capacitor-next
          port: 80
