apiVersion: v1
kind: Secret
metadata:
    name: capacitor-next
    namespace: flux-system
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    LICENSE_KEY: ENC[AES256_GCM,data:Ftckx+6SCd/XHz45uiONWkup82eYKwsnZuum1ACqTgwB0hLVUrUzY0gSjV5TmYjtdH37G0wsM9Lf0/Z9xQz434IZnSJ4htajaiRC2xXVirwB2YxmGjoQ6iye+ZK7YjkmCaOvDS89hAuPqNdxyX4ng6BdEh2wwZmdrOJ40XxzAeyG4tSCEvP88o0xtmf2sPVKJjDixJSNP8KUqjAb9qAg6X+vsfA83/8qdPmGPFM7gPQNhiyOjCIxRKJvj7tqMHR/wMDP,iv:Fv72T+tRmLR/iRlvKRdsFM2sU0zXYnGxYTJnh9luRRc=,tag:kjPVFngkIxqpFDprF0rkbQ==,type:str]
    SESSION_HASH_KEY: ENC[AES256_GCM,data:frGTjurd/jaZAr8HoyXQKxuG2EA0CoF0B2owkKZdroVAlM7FTgjlQ/09Z/cvvCWlxtahUtuhAyHsvkzW,iv:y5+fE5bzhcnapjMKAkygXPSrxgoqVAWx5oKQtVDn1PE=,tag:erPqSg8qHO4lw3rTJKntxQ==,type:str]
    SESSION_BLOCK_KEY: ENC[AES256_GCM,data:2xGb0yCvIP3xBd3qHT3ddPGW1ZKskf0liJqBE62zrY1ZiT2Nk0IkM9dezH2QfC5njHJ+vj00EXOlcsjq,iv:GQfMSYe5KbwOqrazwRivabukD+onFToKv0wsgzj8jik=,tag:OVnOUkdGtLpWlTRQazdh1A==,type:str]
    registry.yaml: ENC[AES256_GCM,data:nUwA+DsAB2LX7NDEV8cDVNuO9zgXJEt9LfZtNHNY4vnw9qynadKXyfqz3uwgjqeKuTJbUMiB3HKsESzOnPEkBOQe9N3VhSzf0tv7xz/NO6sR636nIGd4c/vfiUem0xfegtf2Tm5e/7jks+7/WRCxABg1XlPuEW4/LHQ1sNq8qYZ/0J5FuI1KmvJHkDkXPrK2JQeUeXMOfAGds2dmaegVGgkXDxnTdytEY5Xlx93Iky1o8S6jrdHomK3EOvKq4VKe/b8RttF3MZlpLWwTUpcAaAhI9wWhGO5Xf/gBt9G46d7AWA7BWyWhhht5h6v/oxF2EtXvR9ioABRgyc8TWs63uh7zmBQPIBFCIYU5jExTJA==,iv:G0fgwXojR2n65rzwir/pRYYrCt7XuaEZ4wx4IfmO1JU=,tag:gqtUXvwq3E1w6eRBuQCnZg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycE5Fay9JTlJoVnpmY3lM
            U1VFNkFXSVdVSXNBUEVWbjVjZFBVTWNRbVZBCkxmK24wM0xPTTRwMTFSbkY3cFVQ
            WDdjV2d5WERGMHBrRWVrNkttaU8zcGsKLS0tIEllbTNVZUs3aFdzZmRvUFpHVkQw
            U3Z4dFBqa1hpME5wRStRQ3AwZllYM0EKrdcFgaZkCBtMUModndWkXDwnRnO/atm3
            lhFT9WrWfM9PR2ol+QNGezcHv9OCpktCVpvKqq2NcTabSuSkIGxXeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:12:09Z"
    mac: ENC[AES256_GCM,data:nmV0/WIgRvqvOhNvyXGC74NqEdB+Mhqr9NrtHLkFvW2qh9BCYpZOSE8z2E1rY/g1ESZohczpu0GJhY77Aw7eTsxuAJX3e1RrZ0/MLNEWA8wOYbok+0H3CTS0bqL2NQ2hT2YYlsYRfwYCOcsTVQcXOcsBFladcral80sL2xAkJZo=,iv:kGpKtv/BHuvYYM8wLgsuJvzdHsLCTWjyE9OGbYGPduQ=,tag:aCUsOpGlB4LSU8DeKivMZg==,type:str]
    pgp:
        - created_at: "2026-01-05T00:12:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAhFqfgZuPOEEw2aBWdVaJ5nyJqBEW6t+GABgeyaauvR0w
            PycQrCGBFiNY6LOwyJM1CAQ7yXEIE/xRaf/1BeZum3kU4bTwM8NIf6rLD0Zn4NlX
            1GgBCQIQ5r/0Ya8qYUJk8+XIJnHRIMldYfE6ICFzmJLM0AtpDzEGTfWsDMp779bB
            TO8TX1mY8XcBlIdyAGQ9POb0uPrORMBt6dLjiteQk5ZJszw8ZWMijVGKmsE8MHoO
            fjQq5knU5/OzsA==
            =/+6W
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
