apiVersion: v1
kind: Secret
metadata:
    name: capacitor-next
    namespace: flux-system
type: Opaque
stringData:
    LICENSE_KEY: ENC[AES256_GCM,data:a83NIW3BGlnC9OeMQGNj4sduY2xkZz7JbfJY6oavYS7F2z4mriCf4ZHVN12Whyc+3O00LyqA1Si5P8vE0l+HDDbwbWcdphgRzu3pVSnPNiEr329uqXZglTawYwk7wXNjkAzlsN3PHeZ3kDuUCZb2XMhnCoAETOZQ7o8L46EkLqJiO5IDHfGdjGYONkRYGO/SYIszbLE8uoZqrbtENFMnM2VRuCJgQNleneK+wuCZXgAZD13aLd+kkMI4Bc8Vb/c7Ggqc,iv:Js8H28NLR0ayBRls4xoIIVLxtve/psTAkxzn6jMuCvQ=,tag:kDnjpW+lL6CgdG6axojmjA==,type:str]
    SESSION_HASH_KEY: ENC[AES256_GCM,data:i3X556elfnd2wPmse/Kpa1caD1EXQF0SAwuEpp9xVKtWeUo+N2ee3onc5A1fj42+sqbLMDNTGtWYE1XM,iv:7LEJbQ8R5ay61wdVcJH5BsQW+CgvFHXVIcroHV/1rbU=,tag:/w3gbGTehnQiNJNECz5nTA==,type:str]
    SESSION_BLOCK_KEY: ENC[AES256_GCM,data:ak6DgA1aivlFc8B1sRRcKeYcPCDjXkBcRYy0h73bjHWSKalj7kME6tjFO8LtqL8QTHRN1HR3p3nA7N3+,iv:IJ/LJUJrCbHrn7lNAUZN7XtRLn54vdKYojtaWmJ5/es=,tag:rONojOPLSfDEsIFOHvVZ7g==,type:str]
    registry.yaml: ENC[AES256_GCM,data:syO4h5sicMq5Xx5fLUn/8jhHx56QAM4twBEtC6/mCk8YC7Pgw0+tt5+GVdG8XFEvXHp+O93rRVJtrh5ZWqIxhcxV3zRCGdJZMQ6ny+pJbbM8Cu47RR1LNR5lCiIODCfzVU+RXRC62foZec58DPgu0GLwOdRoIGoE1KHLIqx+yBzax0yQUUpdMok1jjlYP8dfsdhMnBN+jfeunkZVSlS9o5pEswF5pkvOvqcfWzc8LgJvF7vm6aULQfzRjqHQ+rxwT3qM3iEnseEGiCcpwm79dDAeGHYrowEXIG7bBKvCCtFM6ujzKmBkBJu2GvxqbcwLKF8h8xG5Df2ZnJUcWrvaoJeL0Mq0tC0aDUqyY0tSEg==,iv:TRBvgN2Ta98hj8tQfqBZ1YEdsCqy5jU9CUqRsQxmyKs=,tag:2KnhYhgimisemHLM9lBN+A==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bG5jZjFyeGdiUjB5ZXY3
            SWNRNlpUaVJJQi9MbUk1R0VicUtBUllJZEdRCjB5d1kxYTBrTlNHV3A0YVU4dU5k
            ZWkxK3dkNmd3eEF5RkROeFBPSHlvaFUKLS0tIEZsUXVzNnZFL1FRVWJYZE1XSGhI
            MXluK1lBZ25CbmZBRnp0U2lZSE91bUkKT02avpTShrqlILVLGY0d02XO11RGdH6s
            JJJkkYmPgl05zl3kwCiV0H9URFMvoRBD8A2tb8ggUrjMYrqgxZTJpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T21:13:32Z"
    mac: ENC[AES256_GCM,data:xTedcE7kUGJCKH4L9k5SL1GI8adCO4Pgy6hnVkJTS9SXGzUNacFJmGTMilqhOoeSJpUCNaNMO0zDEfWpmJn23GkEkRnl6QLAAyVaFrCKDLDhYGwJBbiJY+H/d5vlB1tttUGASH+/8OnhtTHfFDuJvbVyCiJIlrWBwLBuLEQmcqk=,iv:+Eq0zNmY9xlbLnidbrAu1dyYqBSsBeeV0SigUQ2JwtQ=,tag:pk8oQGTsPoH3390EaWbbFg==,type:str]
    pgp:
        - created_at: "2025-12-21T21:13:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA5P1ZzCH6rE6BjVVm/1/Hqzjhfy1DeSPpsJOEW/1IFg8w
            uvIhhpO3tZRJ0aJYRQQOl1l62AYHYGAFaigXT773C43Pq8Lq8H4ARPA8OhLhkbLa
            1GgBCQIQBtnWpiS3qxnxUm+EtpW+WCqBYwARhqIIRvFtOSvDF5bS+IJC/sSOxtay
            7Ywj1dTt6m1A++3V/gXGJcN1NSyaOdfFw54BTH+Wb6L7nk+zhwaRLQ1nMtKsq1IR
            kRqKDbgTq87QWA==
            =bULW
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
