apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./actual
  - ./auto-rsa
  - ./brave
  - ./code
  - ./discord
  - ./filestash
  - ./sponsors-bot
  - ./warrior
