apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Metrics API
  # https://docs.siderolabs.com/kubernetes-guides/monitoring-and-observability/deploy-metrics-server
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/v0.10.3/deploy/standalone-install.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.8.1/components.yaml
  # Monitoring
  - namespace.yaml
  - ./gatus
  - ./speedtest
  - ./victoria
patches:
  - target:
      kind: Deployment
      name: kubelet-serving-cert-approver
    patch: |-
      - op: add
        path: /metadata/annotations
        value: {}
      - op: add
        path: /metadata/annotations/ignore-check.kube-linter.io~1no-rolling-update-strategy
        value: "Can't control this"
      - op: add
        path: /metadata/annotations/ignore-check.kube-linter.io~1restart-policy
        value: "Can't control this"
  - target:
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /metadata/annotations/ignore-check.kube-linter.io~1no-rolling-update-strategy
        value: "Can't control this"
      - op: add
        path: /metadata/annotations/ignore-check.kube-linter.io~1restart-policy
        value: "Can't control this"
