apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Metrics API
  # https://docs.siderolabs.com/kubernetes-guides/monitoring-and-observability/deploy-metrics-server
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/v0.10.1/deploy/standalone-install.yaml
  # - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  # Monitoring
  - namespace.yaml
  - ./gatus
  # - ./victoria
