apiVersion: v1
kind: ConfigMap
metadata:
    name: rathole-config
    namespace: rathole
data:
    config.toml: ENC[AES256_GCM,data:RVPJ4nl37uQrcSzzPY5OBOhPR1Qg92m8DgxZKHc00YIwfn/Jo7tjB17+rc24cua9Z/Cp1WlLdFE2KbtNEhJtKqjL6xf6OiGycne6DNVNfXABhyh1KydEtP/2HT4xrKWrZaLW4JA1r7Zxam5Fk7YpvYfFSAeAUpIM4ynQxYeuEXMzAfOCkXPWfvyqXpcJPjAiDhk7Jm6RFzfnI8kMjE2qt5ba+e5DFN2qxhX4CxJNTkOaYg6WPkSmrLbyrZgNqe3LITo2AEtx6AwhGupOVIwvseXS7Q==,iv:dFgOZryqlCZ+wyJjcqQgzTyfIFokWtvIfHZvEf/nIqc=,tag:oRj8ng6OCkitzZkh8byVIQ==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWmg0Qk1DZ1kxYXMxNHBM
            TmlvYUwraHl5YUZkdFZYUTNrUjFYLyt0QURNCnBwK2FDYW9ZdU82WGIxLzNSdXRr
            RDdsVEJ6dG0vRGo3RXBmaE5ZWnRDWjgKLS0tIE45bGNtK2s2dzJpc2ExVkREekxK
            bmlFbExudS9CcmNNMTVtRGNTSnVhcmMKZ8gpnhXo1/c2Tp+auga7b9e7vUiaHEZs
            u/q055XGsQqDuxMUHvLknZs/MmxViksW4kqrbqykhMiIGjumU/CNOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T18:42:18Z"
    mac: ENC[AES256_GCM,data:fSKPfilT9qzsVhZUXawp2AwajcAV7S3GDkIIsPT+81PZ419S4dHJjLwfNshDhcPMrBTBruUORt6CyxHfxLGu1wDSEUx2QG1JGMA0ogPnOZn9vawkMeRRTyF9D1qzkCktZTNI3Kp6l/qllG4z2dDKvtQ+njfh8WLV9N6TfPNN7Gc=,iv:b4SWM7dj7dH0Gi9MPU44l5a6/88xnbYPLyw7tl6uIGY=,tag:vmFJ4r4CZtNqWAaVDtG16w==,type:str]
    pgp:
        - created_at: "2025-11-20T18:42:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAxRWAkNRvr7mwWGrxPEaPu4oVRL9p/w+xqgsOay4fDD8w
            NYInyL8LxlQxc2Ks5aWwiTwNPQpYYmQJRBoMmM9kXNUBS2mC+0qByDTxcOIrzJ4A
            1GgBCQIQgsni8F8HRib2+FJ89ud4cMczG7opoY5emBO2Y8OfKT3Bq4XsVEuNulJ4
            oMcMkzs7iw2h5O1CI561ij2FhipmWTuh1l3EP18t8yJk6R2nE5JKnztccPn3CKlt
            4F4X7sf+TgYq3g==
            =l8DB
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
