apiVersion: v1
kind: ConfigMap
metadata:
    name: rathole-config
    namespace: rathole
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
data:
    config.toml: ENC[AES256_GCM,data:u2FcnsGkWiMc99e/N2GCz9ruEHOrd4lLUs5hJ/JZP7PZ/aHxoMj/VaroBVCjlPP75sQMODQ+MzmSHk7V5h8vBUNjaQL4kZ0BqBS86KZH7JUSeA6i1mdAY3OQolC365wT+/+aO5n2v3yzt3BzBjPtSUZ2awtvP1PhQPOAmP1wN9CGp8l6quPrUdP/op8jWlJ/o/td1tmq9k9mAwbEgQHJfq+PumHGuIWYLmlTKWzcISN6tr2IGINwTRtTaOvmSGYRTpEJ9ZIcy6TsrcySGPaHXUXw3w==,iv:zBhQTu4n6THMGlnRW7MweCrZ/Qt7wwDtA402f0xAl0o=,tag:sHFr4jWUo2FyRWPSyDeVVA==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNzdiVEpIbDFZaDNIZExR
            VHZUQlg5MlFjM0dNcUx6ZGVoQWF1RzFlZXd3CnNodTJ3QithTkhWY05PM3loeTFl
            QXh6TkFZWUdPZForYXJZZnV1YWxyUzgKLS0tIHkxZGMxUTJOdWt1cWxTVjBGTnFF
            ZGNGVTlHMHAxL3VxTEE4cDZHSnlzK1UKHC/MNJsPOs0PhrKMNxTeG8izSAcMGLJg
            3VNlGpI75MZ3Ha68heZIi1jdoumbekcvqJDmGNX+nN/B+yKk8qJL6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:12:43Z"
    mac: ENC[AES256_GCM,data:0DD3fauggwg0d4/0kU2v6eYClpPnMZBIQP+1k7wI4IayP28Re59/vGDdisqcMjB9l0Gv54lPfj+NPAfLJE/UepTBgVRBOsoJg0RTcPUbIibAuY9fZR1+gM2EbeZ3PzOjridk5oJRB/joj5ZBIJHy1Z9+ID2fsYqfPyoICaf5fyE=,iv:DH9xL32ip3hsWMBuZ3ITPHB/wn/jLmEaDBJnAr+WmAw=,tag:Exg82Ac/C58JkaPrk4IyPw==,type:str]
    pgp:
        - created_at: "2026-01-05T00:12:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAkD1z6xuIgyCfvnOJx1kE5EwK5/iTMys0Ut0Ezd9pdlkw
            o+wMqNjc+CvXGPd+PhZAqJXbkQMgDqNQ3H0Y0XJWH2yVpGm+BIjStS07hUw/RA1t
            1GYBCQIQAUwjVaruRWi+tmpR0tZPda20DkAtZHaW0z9avVn91zqSiKL/iLcwOlBq
            uxb+rqDgMrxBskiBHVSfS3Jg11SoHRBEeBRBWVlnyPN4LKmoPoBrwArtYj7I9lOb
            WEvBDB3qSyM=
            =EKnu
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
