apiVersion: v1
kind: Secret
metadata:
    name: rsa-secrets
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    #ENC[AES256_GCM,data:C8BtcWWmALb7QQhy9gQSB9Xj,iv:78+o5uIZveM2UtKLFnkjL8Y3Ai4+aGqTw/BGRAUEJx4=,tag:hu8TdNV60HqgUnEhAm93Ew==,type:comment]
    DISCORD_CHANNEL: ENC[AES256_GCM,data:aMs9pf1mOcfWO0I/sdG5U3O6nA==,iv:av3WdecFXhR13QCIfBTvWuL1fc5IQl57wnRN6i79QlU=,tag:dCzaVWGVxQtulm/YAAKi8A==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:xPh0KliKDnrxN1g7WiVBA3RgosBP8+vak2VfXSIqELt4ZyTRLu/0CMKNMg4dwQKyrUghGMaPW44tOv2mkrLw4VIKos61aEQT,iv:oVp3V2Tt8rGeN4ZwKTQQ68/si1ZaSJOcKBuEvxp0/ag=,tag:FIkyhXGAflnnG3lhHrfULw==,type:str]
    #ENC[AES256_GCM,data:2wDwXU4=,iv:Qo4I1o8wniBEU2MUr6zVfNpTEYnDr/F+FpREKvVdcFM=,tag:U7QkmSc49r6NNj/Baoufzw==,type:comment]
    BBAE: ENC[AES256_GCM,data:At4MVWSumPdsUs62mr5pxMOjTaiaef5l2ZZ+dE7fa48tQxBAg2VLDOdA,iv:axBlAnEGd8ptAqJZfeLytux1kss/Xwn5eMxECIAhAUk=,tag:ZUPteJZ24hM4So5j/1PnqA==,type:str]
    #ENC[AES256_GCM,data:gsx1GuN9,iv:gr8mN3QSqKjyWvFOmloOdzrND9k8MCPzTi7bKBNVfe8=,tag:jbrigN4RPwbKMOXRZpsjtQ==,type:comment]
    DSPAC: ENC[AES256_GCM,data:HuBjYDFjsha5Om6up7hy70ZsASBvWzge4qpgvRE6kBzH7h8db3hk6QHo,iv:rKiuC4WKVPiFlfGNkh6IP+zRRsf1jzUuWjOYDHLOZrM=,tag:ccEXFQGaqfd5iIqdIeZyNg==,type:str]
    #ENC[AES256_GCM,data:gDCBBCDToQ==,iv:yHw7S1Z2LQoP3B1/gNgUi6EXszbWqRdtqM0TM1JWe8w=,tag:gG7/som2TUz6QuTTXlA6vA==,type:comment]
    FENNEL: ENC[AES256_GCM,data:veLHM56JFZoC6DB/XhRi3bBkOVnt,iv:SH0bSRSaU/+N1gsskGLfSWIu0eSda/TbAOElNuKs9as=,tag:TrdwhyEymo5K5Z4gZLAE3Q==,type:str]
    #ENC[AES256_GCM,data:CyH5hzGXNRmJ,iv:V8g1/EpMwEZvngRLWa9LKYEIRglkU89XRsh+9yUekrw=,tag:Re6tsaOzidg2eDBR+DXV5Q==,type:comment]
    FIDELITY: ENC[AES256_GCM,data:Cu80aQrNoauWe/ZVKrgr477vNEgZcrd7GMAklv4JfA==,iv:s7IcYXgMzp9AcNXv9pIR8f1+oODqkHP9x7GRfQX0g48=,tag:bZi3B2UmNMyXYBSTRFNu8Q==,type:str]
    #ENC[AES256_GCM,data:kW7VHbCsCA==,iv:jvYuI86gSJBnY7IUG6B9fVhbiwJBRshCpYKplMsvZIo=,tag:4Iek4Jgu5baw5Ttc7tb7ZQ==,type:comment]
    PUBLIC_BROKER: ENC[AES256_GCM,data:adLPyVXepIK0s0oYvfEJt6NuHRRkU9GtZ/FdxslT8n7zxE3pswjuVBw1slQbZWgnX4B1YGh0TndbIVwWxsKOPykW0Ad5CQCfRuxKC4a1J1nHvTno,iv:s40ED3RVptHsQMYM1IqBsO+CfXsUHTRjHHOBKSxMPrE=,tag:wbJFj3TLFxYY1Q3SyqqSoQ==,type:str]
    #ENC[AES256_GCM,data:yZrgjv4w9xwvwA==,iv:jvMlVBPqRY+lq/N1KO++Q12/10aUT0mdHiQwphcRHKk=,tag:VCouvNQyWn5MHyx/MRMikw==,type:comment]
    ROBINHOOD: ENC[AES256_GCM,data:RMwibM/MVCyXG6ZR7zoaiP+MF/j0rivLebfrUOBOcK2kLIzWp8hAFuKoLNdEn7kKB/Skhw2wHiyUX7hN07sM0MzoDBfUORCdsg==,iv:9IM9lidBEeOerY12JTXUxJSlgT+tIjTeG7FaVeQBVY4=,tag:SAjXQJonTozspl026kfxdA==,type:str]
    #ENC[AES256_GCM,data:axD1ETyfgw==,iv:rEJiYxUsnUMvr+/+DDY9jtMCE+nYCkG7FLwyatqemus=,tag:ChqSyYqNAMaxr5Uyp7UjIQ==,type:comment]
    SCHWAB: ENC[AES256_GCM,data:XpAdUnYIwbZEj/dKTPt/0i9hijINBWI0+dpMiCbo5nOi6qkdpuACUP//tdPviiFzKQ0udkodT3e3fA1LzqF+Vg==,iv:YIgrRKAqnZM7Q8lOStCMwXPm7iKEhbwLUeDQCzCg9DU=,tag:LMOPPaDfFrVsGM81+V9amQ==,type:str]
    SCHWAB_ACCOUNT_NUMBERS: ENC[AES256_GCM,data:BXDae6IWlK4=,iv:cjvdCb4nkHdklWVZ6JqCS4STYyWSiAlb5sjYd55coug=,tag:ZcAtRwpRsc9A12aAvRTuAQ==,type:str]
    #ENC[AES256_GCM,data:X9mQDf8hEjHpz0c=,iv:NT7QT7I6XyY/pdqH0lYMOU+Q/OcCwByePuO4Hog1kng=,tag:OOdsy79D1gQ0NK4m2msnhg==,type:comment]
    TASTYTRADE: ENC[AES256_GCM,data:gEQLzk9s1NEJEXwNK/51JzHlgXIHdhu10gOMbaeHX8rh2ziuS5nv17AB,iv:OBFot2rzfijo7pV8rmVVegvK17oT+YHX+qZJBdlsrh8=,tag:Ov/aX9+NUPTs2Z7RJF23uw==,type:str]
    #ENC[AES256_GCM,data:d7s5HlxOaw==,iv:ATD/dd/iD/mVRuJFmak4g07AitkrXSFZq+gxYugOFE8=,tag:4CfK8MZ6I5E29DAM5+6htg==,type:comment]
    WEBULL: ENC[AES256_GCM,data:OtDtywDXtc88hGriuZwDkDX+t689RpbXNEoyDCcGgI9jXfGk1+5UKnbeJYhpLAEI4muqKGj12HxEGPtRG7oB/PLUbRnhJu5otxQz8BCdZi7lYQ==,iv:hh7MHUZXpFlnxvgUvtDvxayrB4ylgOlZxU2BARXvAw4=,tag:jomnb7RuVkVuPPn0ZGHNcw==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbFZYV2hhR2t5clZ4SHdZ
            NFZleWNqaktwajNpZ1NIeVYzU1lOTFlTd3lBCmI4WUtVUWhQRzYraVZpMi9udHR4
            N0lhZFhMcXAySXlaMzVEZEZ2SEticjgKLS0tIElWVDJIM0dHdXVQUEtTMWNGTjVn
            dE0xMmRKa095dHJCK3ZiS2QzWUR2ZmMKblcdPThfUbsnuTJTeCgHwDLr+FlUGrZt
            L3iT6fT6Ofpt9U3L7IkGtf+/x5ph8SST2yOyjdHU3tEo7BKu6GKzDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T18:21:08Z"
    mac: ENC[AES256_GCM,data:zXrsgRRxFFNJIcyGVk3UcOT0dMs6uyWbF8ZTygk6RhWsvrzgy4XWa/BJ7dyRRPeS0nvQgHhnpkwcmlvJXwQBd3cficgZxb1ONaNDewt8Kz5Eoq0OUGeK7zorBMFHeavHUjhAAk3mJKDgSxxE3iLK2BNSxg+n5yLkle1kqG6rezQ=,iv:2PNIDI4d2nSDuusl0rLQpwDmBevN3k+ENsq8sZVlx88=,tag:572uLNK3XVbI+vlbcw1NJQ==,type:str]
    pgp:
        - created_at: "2026-01-18T18:21:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAhADXlQAL49vaJVmsN8pPVDlMCjY0yOi68Gbkt5sBB2Aw
            q6P6Z93Is0EfgZkyNTIVXXOYqsE1OUiRdYFMbYd82bB6ASRYvVqCso3hh/MK9wtC
            1GgBCQIQtez/dckB//k7a66rSjn5GKtWWZbexIkhT90uwi+Stj+DJ8aqmDWGCLZ4
            /3CN0bFhN/IjRJ+80rIS4LdBqQN5ed41LgfRZl4+++A1CdvrIrUvp/SJjVvTuT2l
            alow3PFNGCbymg==
            =myZU
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
