apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auto-rsa
  namespace: apps
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "Browsers generate files everywhere"
spec:
  serviceName: auto-rsa
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: auto-rsa
  template:
    metadata:
      labels:
        app: auto-rsa
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Always
      containers:
        - name: auto-rsa
          image: docker.io/nelsondane/auto-rsa:latest@sha256:55379d4162da83b85bd539bf12ec6eddc0ed7ef389e608590e081f9595e62898
          tty: true
          envFrom:
            - secretRef:
                name: rsa-secrets
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: rsa-data
              mountPath: /app/creds
          readinessProbe:
            exec:
              command:
                - pgrep
                - auto_rsa_bot
          livenessProbe:
            exec:
              command:
                - pgrep
                - auto_rsa_bot
  volumeClaimTemplates:
    - metadata:
        name: rsa-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
