apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auto-rsa
  namespace: apps
spec:
  serviceName: auto-rsa
  replicas: 1
  selector:
    matchLabels:
      app: auto-rsa
  template:
    metadata:
      labels:
        app: auto-rsa
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: auto-rsa
          image: docker.io/nelsondane/auto-rsa:latest@sha256:141443cdd8144a45e80d59a01c195a11fb11746d4381311ecab82c51559a8208
          tty: true
          envFrom:
            - secretRef:
                name: rsa-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: rsa-data
              mountPath: /app/creds
  volumeClaimTemplates:
    - metadata:
        name: rsa-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
