
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qui
  namespace: vpn
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: cilium
  hostnames:
    - qui.cluster.nelsondane.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: qui
          port: 7476
