
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr-ingress
  namespace: media
spec:
  ingressClassName: nginx
  rules:
    - host: overseerr.cluster.nelsondane.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: jellyseerr
              port:
                number: 5055
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr-ingress-public
  namespace: media
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - overseerr.nelsondane.com
        - family.nelsondane.com
      secretName: wildcard-cert-tls
  rules:
    - host: overseerr.nelsondane.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: jellyseerr
              port:
                number: 5055
    - host: family.nelsondane.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: jellyseerr
              port:
                number: 5055
