apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn
resources:
  - backup-target.yaml
  - helm-release.yaml
  - helm-repo.yaml
  - local-storage-class.yaml
  - namespace.yaml
  - recurring-job.yaml
  - route.yaml
