apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-resource-driver
  namespace: intel-gpu-resource-driver
spec:
  interval: 5m
  releaseName: intel-gpu-resource-driver
  chart:
    spec:
      chart: intel-gpu-resource-driver-chart
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: intel-gpu-resource-driver
        namespace: intel-gpu-resource-driver
  values:
    cdi:
      staticPath: /var/cdi/static
      dynamicPath: /var/cdi/dynamic
    nodeFeatureRules:
      enabled: true
