apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel-gpu-resource-driver
  namespace: intel-gpu-resource-driver
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/intel/intel-resource-drivers-for-kubernetes
