apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive
  namespace: apps
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "It clones and runs Python and other scripts, needs write access to root fs"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: archive
  template:
    metadata:
      labels:
        app: archive
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Always
      containers:
        - name: archive
          image: atdr.meo.ws/archiveteam/warrior-dockerfile@sha256:db162f841c520696c3d2655efd4fdbbdab7c3f50f338fb6d671d6f875ecabf58
          env:
            - name: DOWNLOADER
              value: "GamerSnail"
            - name: SELECTED_PROJECT
              value: "auto"
            - name: CONCURRENT_ITEMS
              value: "6"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8001
          livenessProbe:
            tcpSocket:
              port: 8001
          readinessProbe:
            tcpSocket:
              port: 8001
