apiVersion: v1
kind: ConfigMap
metadata:
    name: frp-config
    namespace: frp
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
data:
    frpc.toml: ENC[AES256_GCM,data:TPHwMBB01m5U33Ue6kci3Bv6WJjTlz/Gwdkg3MXdJ6aFGSOUgf8+kO+HgXu+BLLu0sxMF9v4QYEpTeGE6i87SRK2p/moIz2IT5JpBzXK3xAYS80epTYL4ovT9O6OFesxUkZhKKl7dea+BDkXyVGynJO0+AFP6u2BLnBLgik1KNu59Ff7tvvNvRnSb4Mn+pzsK7HFZ+0rw2msxpEkMZGzLDHMd5aRyRX+AMfaqO1MLn0XKKVHkJkG1eWwNi50WWeg1Nh88JfdoEZBVa7FN4YMAj93qSd8cwxjvklZlBXkZ1QwxXEs4G46eO51uE3dOdE4gX8U3fy1soKvSfNchIe/ys+s44NI961w+wmAHFkrMrGbnvSGtLFgu4nE,iv:gqGk6/dMx6NVcvx48Lf88EeTLX3R87MExymrRSi6fMo=,tag:dh1XZNyoBOtA6OqSmuLYjg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTlNkUXdyS2g1SEdnT05W
            dUFBbEkvT0RsNUk2VXBxYWhOVk5xd0RBaTNvCm9IUWc4QXhpbXJKTDhiTmd1V2c0
            anB5ZlJoUVFQVlhBWDJ6VmdWQ20yUFkKLS0tIHJVZjRDY3JabWN1cGhhUzJ0Uk9H
            dHNxSjBhaW5oSUo0RUtoWGMwb0l3azgKraqQVGPGx/akKpiuFmAPwSbMOmNx+vkC
            cKVSodUCb3xB9ck58MGVH34iw65z68tIla4lhBzGUtoC7FNoe8IdIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T15:50:22Z"
    mac: ENC[AES256_GCM,data:ZhCn9LLjTe1Wd2Cg0afvXP5/6gyPiQUJ0bJNR1HfI3xnE29cbaFJXJl0zXdvmXoF2KCMeoY6Nd43YRScEevJriNpRCGXzE4jAgk1Cjtrok/VkGwsR3qw4SYeoGbvznfHA1Iwcd7aaLaKqdW4rmdj0SbwltpmWolvsjlFnsJBIT8=,iv:cQgofoHfM0Vh/bHygv7T2Klrqi7JTAT9nyj1xiwPZyg=,tag:b0l+bX9uWkXK41BeKJM/3Q==,type:str]
    pgp:
        - created_at: "2026-02-13T15:50:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA2gSAyP8A01h77hdt4zoPzHDL7iYeiiJxHYA0jrTXuSAw
            uEzfELkLo+o+OAxGKQn2H6sTLCd5Mn9WoIZzhQTusWaUTKni/nh8AyaJfddtvgsf
            1GYBCQIQL0nB22CWKrRiK+o76eAvNo96y51vOpdgkH6svXdknfdtzZ6zzoyHXrou
            KkoD2alo98W98+xI4GvkgrjvonI4yaLGAaieHt0wyx7BsoTwKRA0x7tgs18Xo7OZ
            fWwzabig7vI=
            =KPoZ
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
