apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Shared
  - media-storage.yaml
  - namespace.yaml
  # Apps
  - ./cleanuparr
  - ./huntarr
  - ./jellyfin
  - ./jellyseerr
  - ./profilarr
  - ./prowlarr
  - ./radarr
  - ./sonarr
  - ./vpn
