apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: vpn
  annotations:
    ignore-check.kube-linter.io/drop-net-raw-capability: "This is required for WireGuard to function properly."
    ignore-check.kube-linter.io/run-as-non-root: "The gluetun container requires root privileges to set up the VPN connection."
    ignore-check.kube-linter.io/no-rolling-update-strategy: "Using Recreate strategy to avoid issues with ReadWriteOnce volumes"
    ignore-check.kube-linter.io/liveness-port: "Port is exposed via Gluetun init container."
    ignore-check.kube-linter.io/readiness-port: "Port is exposed via Gluetun init container."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      restartPolicy: Always
      initContainers:
        - name: gluetun-server-updater
          image: qmcgaw/gluetun:latest@sha256:7b1dafa3d25cfd891deae52c7973c499f619f7d8eac52fad84f9aa1e5e6e01ca
          command: ["/gluetun-entrypoint", "update", "-enduser", "-providers", "airvpn"]
          volumeMounts:
            - name: gluetun
              mountPath: /gluetun
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
        - name: gluetun
          image: qmcgaw/gluetun:latest@sha256:7b1dafa3d25cfd891deae52c7973c499f619f7d8eac52fad84f9aa1e5e6e01ca
          restartPolicy: Always # Keep container running
          securityContext:
            # readOnlyRootFilesystem: true
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-secrets
          env:
            # Firewall: https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/firewall.md
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "6514"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            - name: SERVER_COUNTRIES
              value: "United States"
            - name: TZ
              value: "America/New_York"
            - name: UPDATER_PERIOD
              value: "24h"
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: "/bin/sh -c 'wget -O- --retry-connrefused --post-data \"json={\\\"listen_port\\\":{{PORTS}}}\" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'"
            - name: VPN_PORT_FORWARDING_DOWN_COMMAND
              value: "/bin/sh -c 'wget -O- --retry-connrefused --post-data \"json={\\\"listen_port\\\":123}\" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'"
          ports:
            - name: webui
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: gluetun
              mountPath: /gluetun
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "ping -c 1 $(echo $WIREGUARD_ADDRESSES | cut -d'/' -f1)"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ping -c 1 $(echo $WIREGUARD_ADDRESSES | cut -d'/' -f1)"
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]

      containers:
        - name: qbittorrent
          image: ghcr.io/home-operations/qbittorrent:5.1.4@sha256:25fc7caf22101f85276ede9b1f76a46b7a93971bb6b70b6c58d14d6ab7f51415
          restartPolicy: Always
          env:
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tmp
              mountPath: /tmp
            - name: media
              mountPath: /downloads
              subPath: qbittorrent_downloads
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          # Using the actual API requires disabling auth on local, which isn't enabled by default so it would fail initially
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            tcpSocket:
              port: 8080

      volumes:
        - name: gluetun
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: tmp
          emptyDir: {}
        - name: media
          nfs:
            server: 10.0.2.20
            path: /mnt/Shell/media
