apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun:latest@sha256:7beb357f2b9e0e181812b6f408812e00ef85334bf2dd1b9b6d2df6c5b0bf8957
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-secrets
          env:
            - name: VPN_SERVICE_PROVIDER
              value: airvpn
            - name: VPN_TYPE
              value: wireguard
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "6514"
            - name: WIREGUARD_MTU
              value: "1280"
            - name: SERVER_COUNTRIES
              value: "United States"
            - name: TZ
              value: "America/New_York"
            - name: DNS_ADDRESS
              value: "9.9.9.9"
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: "/bin/sh -c 'wget -O- --retry-connrefused --post-data \"json={\\\"listen_port\\\":{{PORTS}}}\" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'"
            - name: VPN_PORT_FORWARDING_DOWN_COMMAND
              value: "/bin/sh -c 'wget -O- --retry-connrefused --post-data \"json={\\\"listen_port\\\":123}\" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'"
          ports:
            - name: torrent
              containerPort: 6514
              protocol: TCP
            - name: torrent-udp
              containerPort: 6514
              protocol: UDP
            - name: webui
              containerPort: 8080
              protocol: TCP
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]

        - name: qbittorrent
          image: ghcr.io/home-operations/qbittorrent:5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
          env:
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tmp
              mountPath: /tmp
            - name: media
              mountPath: /downloads
              subPath: qbittorrent_downloads
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: tmp
          emptyDir: {}
        - name: media
          nfs:
            server: 10.0.2.20
            path: /mnt/Shell/media
