apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:jZLDcOcuvRuf,iv:lpYxEHR8GZCR8tKh/nmzu8oWNyyB6HmFGses3D57grQ=,tag:GIzuMz3qilJdBmBpF5fJRA==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:EmUpjWHR,iv:K+6sUOA9hvd2YyQeRgLPbmQ/wEH79BP6uWDiOWEBtjE=,tag:zZqJRexnXCVMvtxtZ57xgQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:0dnveJiGeSSw4DHV6AV5TIorP/plPfU3beQjYPl4SyhaWEvrTySHXmSEHt8=,iv:7X8BG+NVe6wgpsIzpTB4C/vdALGAyBBVrULKrgw0XzU=,tag:f2QvWJseY08O6hTSrTIwEw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:R6bmcdSUAR9ZzsiuacHNqw==,iv:sBMTUA7/G7I9ZAYjG6bpINX+JDtm3wah1khTyK6/PqU=,tag:zBn+yROAcAyWNxtsmVCQ0A==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:gMqbnimSAf9B7L73SCW+8F1/B1SWV9GYvHywwxnJndK9USJiSb4IU56hx80=,iv:MFIWFKAbdDeuR94ZzTS1NuOEcPXfSa9VjLFDKnB8WUY=,tag:bDe3MZe4seqSkHV1x1cmQQ==,type:str]
    #ENC[AES256_GCM,data:B4o5tkiN8OQf8l0eI/idiMtIiM4=,iv:DSNF4Uw2Euy+CY7CoM+wbnbj1RRA+xYNpbt/WEcjjO0=,tag:rSSHvMFphUvls89c+Ai2Tw==,type:comment]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Wno4S1BHeFR1aG5aUkNp
            UTJ2UXJXRnNkYlZlNXEwRHB1MFQwb0hpOVFnClNXbloxTmo3VVBmUUdIYUpUa3dJ
            Y0RHajhja0R3Vm5GdUFVbEZGRHFzNnMKLS0tIFUrZmRPTFRFM1pHV3JxWGhEcFcx
            SVRmZkkya3hweWlqZTlxSmxobmxRQkEKgRsL3PQb8eaoDUC3AE15BmQP2xao0rIN
            lL1H9WY8EDzicPu/IM3IAzzcyKhg+mHwcuJFPbQBKfPlYchjgZmX2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T02:30:22Z"
    mac: ENC[AES256_GCM,data:FBi8oLZGTH22ZJnCQidNLS3Uo+bYdOtldQagEgy0Gr8IHcvvSVfXPxucjV9z2RZYJIhFTLpL4XgEx7BXC9fkLH9pF3YKYakE1y8fgIjq148/OlKpB8P55b4FraAqyE77UeWzRsdaf2aJa7I7e9MATlC/DkNyl4uBR50yPUNwV1I=,iv:peIq+vW/i4M0ElQHiiQwb7mfCLcBlCy+qwWOvUX+Nnk=,tag:Ht04FhwNUe2sy0f48fBvZg==,type:str]
    pgp:
        - created_at: "2025-12-31T02:30:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdANBlWW+6C9cTGApBK41BJsYyK+TuhNcBAIXzeqNQOjysw
            sKTbhgRmmCsgQKKk58YlcvTs8VOt7A3fPaoomP2vTtgRoPUgQR5ZW5zDA2KIRyls
            1GgBCQIQh5QlCbLU84I0ONTH/OPZBdt1UvZ6i+loEcEVLMx2Hyej3+Ydxx1m1JgD
            AQ/jLfOdtOZXK2en8MrnzXh1C+j3FvTh0A8Ja1j23m0vOnM04MooMz2fRaep8Y5S
            xtlzDU8RunMZ5w==
            =5/dy
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
