apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:f4qJRMis5Ke5,iv:/Ir0UkSjFDYPA8hPP8V4knIxgf8lalMv2GXwwpXhqjk=,tag:o3kymzWTc4mZ8WeC1XoIRA==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:PJRDn505,iv:LlW8nVdzNBXRXLKpIhtcwcbivRrlmIiJGKt97YHkLyU=,tag:QSskMlWRvPMeDNm5pvi/oA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:6xXyHXF2VzkRzywzrdFo7OGBpvJprCikV+LxEaj0vEVXGZmgzWEmOr4aqzc=,iv:szdCjuzPKTwxXBl8JONF4SM+eCUf1j7CdUURz5y66as=,tag:4+VyvoyQ5h46Z36CENqCEw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:XeTw542VIdgC1TA+1UnO5w==,iv:9cqWqopkLJCtHZLGXJLDwo/i6zW8GWD0WmDmD5c2dd0=,tag:2XO8uB63n+qL81k6At1IXg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:ofZts4Ay5aBbiHFMTEOITvHlGSCy+o4AJFTuC1C+zx9QN7NR7cVAg3zf5KU=,iv:RgfAjaxi1tCrFCzg4F7D4fyeAGTp+7Xd1LmoHMWTJpM=,tag:ypnyfyQGQ5pakjIRgNWyBQ==,type:str]
    #ENC[AES256_GCM,data:G07FdI8/519H7RLknrLAmHLgIxE9RQ==,iv:MMNn5PlsFjeogIBFL8pNFyxIhzC/n+aY0K6DmZX0aUM=,tag:JuvXoR0gFkYtzV+uU1JZPg==,type:comment]
    SERVER_CITIES: ENC[AES256_GCM,data:wCBuGFStQllBHaNlGA==,iv:XpZLAA7OT2bhdUGEv47ORdUlcpEIeP6jqV/joRLg8LU=,tag:nsrB7I58/9/4Y9f5OfT0MA==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKREwwRkQ3dUJrM1M0RXRG
            MFRQc3J1QjZubmJKYVA1ZGIrRWVPYW13RGd3CmgvNkFDWGZnbnJPQXVjVXF3dnE0
            NFI4UXFWSFZRbUU3OGpHZUNabHJiaFkKLS0tIGVzNnNVTWJObGtxSWtQMzUyQ1lC
            SzZwbWR1QnJMVloydWFyUng5VVBVdEUKQnxBqt+YQgvle9o+HcvJhp8tL7nKK/6M
            ++EPbhO6vDY2+TNnvZkmx7WPOG/VtAfqpQ8mhgV3CFzleM9NLqQXig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T17:21:02Z"
    mac: ENC[AES256_GCM,data:CPPSoaV5aSz+eUe0hMgFdoj6Re2YoC+kCMTsjppvkoqvj1EBNIWsLvWm0cnSM4tpwzJo64tHaRQiylOXdfFdmguAERE7/DCOCjSChp55qzswDACe74hBmXZwNILsR+sdv8k1+jbEZ2lHpOMTpGwPoz3ylA3SiLaSRMvsF4UjaLA=,iv:BdFX7FxOLrhOe9h7+AvOoXt6BdCmPJ7xlbtBNrL6u0Q=,tag:eTw+f5vEStqcNFjjaWbDuw==,type:str]
    pgp:
        - created_at: "2025-12-31T17:21:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAQcsi1JOCdP9/PhQ/Ee2ae70XTaci2Viy7llUTJXfywYw
            HLbtd1qM+8JnKn3bVTtDg3/QLEDEm2T7YXQV9YPSt1N9Er9upbx/G5v8Nr+JQPNs
            1GYBCQIQD3TLDV6KjduMljIGnvn+2RzQOhAnhpsaNNP0fMv1fTmuxFifEED0fOa/
            nIRkS2tUI/xEsN8ECcRQRfpr1mNR+XUKY+SvEcL5DK44iJx7iz+ixaxYylHXmf5N
            ZUzgUgMVSxw=
            =mZNv
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
