apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:VMLvNEdXbmQG,iv:8xzyICsUHEXGTQ80eWiFxhKJv3tn5LR0eQWFlzU02Ws=,tag:F6cVpx+oREldgiGuiIl2qQ==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:1+zAJpIG,iv:RhgyIploHIDWXF7v1v8bTVA8Oq7T99HDKggLWIcNWeI=,tag:l/DLx0wgikpYEeXoKfxWGw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:mldQ+X+UJg5lPXD/+t4P5nbenwQg2Ds9tnWN44QTX9Ju7W9aEL8BhQtU+Xk=,iv:WUMF91UgvxgO10Qxe5CkPFyDADWb17yrw2qtFpv7dDE=,tag:wBRhOr6U+l8QSF05/jFKRg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:87i9DaJPQU/A9Er3KTzOcQ==,iv:O+T935gAb4La5bK02neT6qxAUyTjA+4JBKLOjgvVH64=,tag:Y1dURcMCLhc5enCNGWzF4A==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:FUPg4irmmjHAHQRLwPG7xIxzCqIyxqH3tcoVtKAmzciOOmSdS+JYPamv8pw=,iv:B3N0YGnX+kAlUCSYt04HjJNMihDoIcxI6mJJecRJQeE=,tag:519LO5eEcZOwUjyW9jcgQw==,type:str]
    WIREGUARD_MTU: ENC[AES256_GCM,data:USwbMw==,iv:JAkOHKdE0RbXLR5CKIjDxlR5rgOZMXT85ZRJGfbR11M=,tag:i4DXYJPp7yozu++xwgbGyg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWDBXVFJ3dXFQMVV4djJz
            M25VemJ3TXRwRUZIWlVNMHZRc1RncldnL1IwCmZ0ZTJnNnpOdEhVYU0wV203M0JH
            YmlIUURzdEQ0dm05Z1JUNXc2djM0Uk0KLS0tIHVuLzE1VTNuOEJRZWd5N3hhYVJI
            TWcrZ3BySnRQQlVWbStqYTVQeHFDRDAK8jrqJuGbguf9qzP4GKLM2G4lrB7FL7qi
            LaeLWY3yTsxh5xl7u7CzSg4AaY40MppZZXu6r5QEvyi8AazRjjEX7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T16:03:33Z"
    mac: ENC[AES256_GCM,data:TCHyQBnDwE5JUwAEQsO8SEJxr6ioyiWZvmVwE2gOyBiLSZV89b2mZndckXVkbb8kEBhgcGB4tSRHeGpCfvdqY23wh8080V20/14rtsJlFvHW291jD4VMNkhIeIq23RYcTYvD4pr5I6qS72f8Qy+XGoQjiUCLChoBne8MbF1BtMo=,iv:1gW/pIl6+3I7nsP85mQJJiPo382JgC2qyGdQXDXRQCA=,tag:aOTXRWaDct2CYJvxqZuvpg==,type:str]
    pgp:
        - created_at: "2025-12-31T16:03:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAxH+W8cJFKkZL2mq1h2Tg00IHIwnSTdpYHUupU2lE70kw
            D6cxjCCJYC+YiFZ2jieJmYjEha4988ZJcRmi/Jayf3rlE0jOfHpMtX4FYFlbSCEK
            1GYBCQIQ1cYsTEjM6CPYUNkQZl0QIK2cpDiPYPOUqn3FMiJ9J57Q6CrOfSAw3O5k
            syYWHXWJJt8HCQX0zYBlgcCC41TUY/ziW315/SKw7rXgt5akP33gG8cHsoB4pcwM
            5dhkgxZFd/o=
            =5svz
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
