apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:OEuJ3a6yf63I,iv:G1C0RMLvYYDwqWQ9OL75K+LiUYLEsX7uIZQCzrphfmU=,tag:Po0nBp+0SI4N9JrLtHe6MA==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:pL7l4QKO,iv:7rfIepweZLh4cS08XJDiwY7A/DbfQwkGwkSVPs5kv7g=,tag:yYk1qvhvh0lJBuyH0aaY2g==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:dIqumY/jFTE24lG4Zvq4fsTF8yyYVH8BSYM9C4RA3Kd2B+luC2z8SDd/ct4=,iv:+MUbaryZZUrp4QWDqj4Bib4aKeIOL6/L/jOPwSrr0f0=,tag:fO2DpzXZ876yrADSyE50VA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:NA5Mb3nLsmR4g1TFDYHA+Q==,iv:nLY9RbsMtEw8C5OU62Vluwe/Rntor3e8CS6LcO+3vBQ=,tag:bozKP3ONVOQ0QjA3RRoo2Q==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:mQWYEBz0s08w7GHBLKFvjoUm4LJFKsvx6szyZn76ba0ZHl+DdI2Gv6EiPQg=,iv:FJHBYHiha+I1WnthWWNSAILt82jwrCfKADwuRp3iOxA=,tag:u/+J7Nm0pOT76cbjI1N1PQ==,type:str]
    #ENC[AES256_GCM,data:g+Io81372jTiq2jPkhLJ4YWeqdY=,iv:Iddp3HZnTijsaiWo7TAFaW34h9o27rVP+bSw0beWHlU=,tag:OUUvscmHxvvN3x0UKiqk4w==,type:comment]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVGM4dSsyV01wbi9TWWxl
            Mmt0UUNKUXhrdzRRcXlQQkZJSE1USWN0SkFFCktzY09iZVVYeFB4MGdGV2Evd0N3
            dEVWOG1WQUNKYzJ2dnFsMmR6dTFoQkkKLS0tIFhqOUxNaVhmVFFkWDNXTldhV0J1
            c1JCUnBEUG1GWGJ4aWY2RkU1dlNFeGcK+MH2t5u0VROFHYqFYJmAImQjE5hV/8Ed
            +LGmMpPWXJaJeiaOSVjyef+MzzFK7xA0v/MJM5v1l4Wx/av3HovTkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T03:26:54Z"
    mac: ENC[AES256_GCM,data:KTuZlLKnBauroVOZXH7qKlF4meI9TeK3pDWZmQK44YOR5RcIQFbGwGeXp+PHiLpPX4TrgqSG8+0Gq2PdjSRK53B8QN18ibzYsG70DWkGZ2bTh0iAP+JWYEV92zQER5f15S63Rb9nrKgdcKHGts9aB6iPd5ayqgHgFq5pegleKzg=,iv:voUdvjkKeCnlbSFUqFx9ycWrgDPGPSY7aiM3XfpBRQk=,tag:lZ9SjGkwRaY02lzMZ7hbNQ==,type:str]
    pgp:
        - created_at: "2025-11-23T03:26:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA4oAMY5SPL0JGZt4lUxNjqKgE1T+LP1mfzJor8UW6tXIw
            g37o/dxhWCipHs9cY3YtUn3+lJEKvb/M3Bh4bWcMhj1ctvGhHQ8jnxu7lIbwhBaU
            1GgBCQIQkCFaFhVtX2MRo0zRP/2nodDI4MM9QBfMF5R2LvVTHgF+vBRnw/hqZglP
            ZRvz/xT0RGPdSH/COTLG4S5BoVlP4oJN017iOFjIymnoHAJt7QzMBDbq/tTp1FQm
            3ctb4UVgKDVjMQ==
            =aR1W
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
