apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:SifK0S6BDmpV,iv:3933yj9tilLWf0hQXWZV61UiO1hkwpAFRN5Fv8NJmDE=,tag:fm/dkHMM712jBBz4ApNdvQ==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:cKVhxdqu,iv:692ep0sOChmINnRP6pE6cb9V1bk0dR+4DDKFT1ihsZA=,tag:jPwS5+v+dseHaiZBiNx3Iw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:W4s0CgKoH0xmj/TUo0LqPkqPdhNnYlZhmbv89ATHodHlFsaXAdNyMnOUwZg=,iv:7l6VRejJlwHhSZMjJiDPq0+dm3hA7DQlCILr5yXpxWQ=,tag:n8Doaa9LS10r8m4DnJJNdw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:zXBkRbZsaIQyZMQtg5+W+w==,iv:jU6qN0FPDc8Mm0M/ZwqqE47O7foMAZ2nSdZYJGN87yE=,tag:NoBZpDWz8RHN6XnDnFxSiw==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:hADawNb654gSh/WwWamIYAd/8PTRkKUz98VYf5uU+I6SAk9Y40HC1P4hz3Y=,iv:YBT8Z/8jTE7bekwiaDuMV9xv/4XLtUBlH+Ho8Zc8JwY=,tag:qaO1xB9pOWdL3hESfCJvXQ==,type:str]
    WIREGUARD_MTU: ENC[AES256_GCM,data:XaKHOA==,iv:zERTzpPHoMPTNHPNkJVTPHb0K4nsz3jHyU8WoKSE7Ls=,tag:eh1HjKtVvOW1EL3z39pkzw==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUVoxVzdKZ0lMRXRGaHdV
            N0dXbHRSTEFrMzl0WHIvY3pEcFM5Zmt2SG5BCmF3VEJldmY5bGp5c1JvaUErMnVt
            U0NEamNXdExpNlkrVTZsZUZSRXQ5T1EKLS0tIDZESmNaNkRlZC81QzdzUmpJTXE4
            MC9uTVVEZG1BMVJ5RnQ4aXNRVUJmTEkKy5uBcIAjz43j1VAfO6whhQiaUUsWN+Wg
            foOfIpo/OjNYlOdYGCPqrHgdPgn36DHzcWpemk3MaOuha25d8Xg2sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:57:51Z"
    mac: ENC[AES256_GCM,data:UDvnBpEiVHBVbl+kytez+kBd5p2YJ/qQirSSqzA0ceJlvMhpj61CzKNadB/hzFstnpYKhGQwt5rH5H69sdqPIfJB1dpTNur5DLrwsBOi5H+Ak9Hc75Gkm5I4NKjd7qwyZZpva5Z9EMNM3cSFoSks77vQaW8Tgv+VbE5ZmHImTyk=,iv:dQxNT4yQ1IoPCFR3di4CDH0l2tc+C/56iv7Kfn5hXwk=,tag:xRUL2r7oCv4/qWnYqnqbmQ==,type:str]
    pgp:
        - created_at: "2025-12-31T15:57:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAunJuQFdccH6DGGVxFVFZjZWGQ/Nzcg+egNgbZB8dXFMw
            q+EssUj6QomCRBOcTGWEvrF277qQU8Lce5vucufcaMEUg10y04e9fUS5gu2d93bo
            1GgBCQIQfUfFarqRE1dYc96Rohk3cxl+YScZ2Z3urYIZ3W6+qlF+bJ7wTjBqpDnY
            9VZvT4tvwZ8oIMSgbdIeAHztcSa9MMPp0cwsRqjZopzs/wwb+YDePFnGBmu+U8yu
            D2aGVjNoAsBITg==
            =JiNi
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
