apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:1ZXLx+YuU5eL,iv:yr7tJrtbqeqsw8HTyRL4rwhEmGTvO0wMxAsFp9q0vkk=,tag:3BT+DvBqKaRaS5asRmWtcw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:Gmf7KJQ3,iv:o2DSi4AGHBUUJ4FUpPB8tHDrNN54TFBs00ZssFBNMJM=,tag:aQCvog1tzfJHk6pfmp5VoA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:zjXopXQQv9oR7VaUcbu3bydo445j5edaLdHwgcTBXzvXUUG0CTu4qCq2l2E=,iv:vQNxmHQ6q3oRTfQGaY8Xj+XKwm/RK6sduZMDpdMTlw0=,tag:+uudgEv/ZBC+6VBhw85VeQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:MeEYYp0DTKNsaQz1FCK4KQ==,iv:0iQghoEpXS2y4TD39XNSUV7vp6F3/8Uyax6vi/goe/U=,tag:GxNMOv175zSjVNbZA8P9GQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:Xs9+m6HKAyHf3nL6tdpXjFk8wf1So5rEo9E2EXZWN4c+OFV7WAwjxys+JX4=,iv:ZcbjH531ru7reRS6z+xMITuHsF017fqOYRo6PKwGIbY=,tag:n2lO0qXUXtW8WPkIV6OxwA==,type:str]
    WIREGUARD_MTU: ENC[AES256_GCM,data:5XTHwQ==,iv:kCm883N3kOEeB5F7JLl0gBZI6tZiOxRzR0bgfeZ1vak=,tag:QqvqIvAIyrzsIFUoRGfmQg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNXVHMVprVzI3aTRHR3RE
            WE51TmJzME16UklLK0Z4c1c0NnV2QkpOY1hzCkMweDIrTjBMR1pXS2xiRFlJUzVo
            dk1BeWVKdlc2QUppM1MxVkdtdGRyVXcKLS0tIC9WRTIycHFiWDdYQU1QbXdTV3NE
            TnVhTUs0UkpQTm91Ky9ONGIyMDRhcGMKnhaOUrO063QOAhmDGqiClYL85IZVInXP
            baXUSYzNv7VS+fltAOqI+Kt5udMGiloIJM3fxVPs8FG3YFCY6zGT5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T22:09:55Z"
    mac: ENC[AES256_GCM,data:IQYWCjkIUoYDVnKZ763tBkp9w+F7UVD36E1Vzb1G3als6t8/4hveBA2weGlu1OPglBDfPE1kmSrLgr08OrCI6H2+jZt4H9wdqptZHO0SkOy7Jxw6mQwRWmkP8/1gDMM1y2qyK5cg3QCFUnxajuo9XNXqUIdlJHDOWPDvq995v64=,iv:DgKmxQ7HgRkpxStIJQMrKiZNtpxG4du2TB8Wkup7wSU=,tag:VeqkyenZDdoynDNGLY5kJg==,type:str]
    pgp:
        - created_at: "2026-01-03T22:09:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA/OoEpHjUkZWMzgLcDsUKQcqPO9fioCgTSEGLobBnShAw
            psuKqq7QpwZ9ERH9qjzTf8kQV4+Y6MqYqsQJgOzemG0KxJsF3v0NeyhwctmXx6T6
            1GgBCQIQj1yx9gFPgwcjeZtyqjxO1vBBUNrYv3TSnJKb2alymRf/8gf4ktSXjzBC
            035YKobJZIcR8TpvloHcmaJygtfhzvykrDHqDYMBQ3HZw+NoTu3Emv93/1+MuACZ
            jEsSWJkVD0rRsg==
            =eRPL
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
