apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:GuNzzAFKyiPm,iv:4CI6HByDCbwyMndHK/1RgL7D80SiMxDQ+lHli5L9Bcw=,tag:YWX4ALRKgBBYw0ic6CPIGw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:isB4jIwo,iv:fDk9G4f69C78iSPKtNvdRSUafrimhJrRSkUiW0kFzlU=,tag:Pxuxu8MUUYhYPHNiBO3drQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:7PoynYptz079F/gUKQp7fap9hTqlGBGzonF6UBwqQ/EjCXy5zy3Xnl4ePRA=,iv:i+zWIsetPMvoAx/LH2/ENoha+PYrEXAKMr3+eY7hGVM=,tag:bynqySkgNcEx+HyqkRUM9A==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:oUEqc3c4Ov9Ni3T7k5v9WA==,iv:ZXyskyOYicuYK2pkiVCy0ZiG7Sg/cRy9689eMYzBDtc=,tag:lhozponntGeaQYU3HVo/EA==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:8IRtRJRJdhT/+LinTVygdi3tDeqWgHm7YoFHIbpdWI0i+EmPM9rbV/W5/6w=,iv:ses3f5uOm1ruupony4BieegJTFhhsOg5oy9vwRFhi/s=,tag:3whALQLnHACuwCeatywhfg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdytDbzkxbHdNSmpwUTht
            VVZHTWttOGF0WGdLaE40MzF1b2NGWU9FTGo0CmJLYTZ4ZTJoU0NvRDVGTU55YmF4
            ZHRGSzdjYldVbmZ5UmowNzg1dkY5ZGcKLS0tIEFHSm1rYXNlSkFHTURNckRSVlFV
            T21DQUE5NVpoQWlBVEVPZzRNOHpuUFEKZzbj72qAgTodR4Y0onujPydtq8R0MB9p
            7POzO7mxLK2rIuijOpXhlCUC46efqmyTdveapjmCy3k+6BYrp411iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T17:52:04Z"
    mac: ENC[AES256_GCM,data:Dz7gVnYIwVAAJ7q094//NRU/dq3RdiDPAxbuNbAe0DH10JwV6IkGbMzSE6Ih1mg27iCfPFCiQ60zcsZjYdFCP2ox+29tGQgPbg2+Pda4t26YNBgDcVLxcNbXBWZIlV1KAcWsEx/OhwO+5jJrxSpGgfUmdWZMJ4zJA2Lrmb40Kyk=,iv:U4B+DNT/XKYx9Gk597I2ulOsEQQ/Dz+ceUPvvGPUnMY=,tag:HrKeVwgFhGcSjsmG7bPaTA==,type:str]
    pgp:
        - created_at: "2026-01-09T17:52:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAGQQJKljy0Un+2YWjzaKoZel4EaiD2pMBuVTPdGDX/HQw
            VVbQJfocLtq8BEW43udGTyjBVYAn0XjebT/S3X2r7AxZb3DVgTOJfvrAr0Ctjza+
            1GgBCQIQIP2IOV3OL/8ddb+w2+lvGeVaiOilYFX8hloDTb+Ac+CSlU2aglIotRvq
            ROI8LsraMg3Aia6mHJLVrhuLkf2h189FH10rDTXwtxYCCspu1TnWuAuCcqTYkM20
            APGEnE8Dqs+SVQ==
            =9INp
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
