apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:KtSRDsa3QPLr,iv:9fBEyAJ/KMnrCZU1dSJKUF4CmCfgZ/krv/LdMWXvYaE=,tag:5b2xENIbyeqcddIdMLnIKw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:WY5F05DB,iv:Yfo7nDVBGnO6wxvnAwcLx8QoWVqlQc7GK94nPR+/PSU=,tag:2hCBceNNvzppiVr1ZmzvHg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:P1lYVYEElnH28Yr0uVPwOaDG1WrivoDN0jIzvie6tC9ykyEnjsH4KsT5ujU=,iv:qxTN17rME62vNFRevYZFNk4QcmMn30um0dJWG7vg5bU=,tag:Uejq3+gDIRVtXbAQ5Vs52g==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:6b0Ly/Hx6auasq876BhUcQ==,iv:bMQZY6mchQ+XZABeHmLY9edeoR1f8VFK/WxC+7UhBEY=,tag:Z2CIxak/YVDmYv6Jrcg4FQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:JyUD4L1SJfvnNQO5KTbPmFzFe4vhvmjweSfP3AQz7s7GquHvNU2LfjjmGbs=,iv:1sNdMHi65Jw+6/YtpQFNpu2iF2D8eDV5OWwRrxsi7WY=,tag:Y3iFGdOiHVzpXVnE5QM0KQ==,type:str]
    #ENC[AES256_GCM,data:xYvktshYU9FhVcDgk0dVOuRXn0ZKxQ==,iv:0rjmIxNMNr3f5WwowM4dPZdjpdfRaNAVnaZSAd+pucg=,tag:aW/uUaquEeM0PfcVJkJDdA==,type:comment]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNXc4TzVzUXNSVElhVnJj
            OXRzTHY2K1ZuSTkvUmRIMWRDWVd0L1ZvMkRZCmN2dS9tL1d6dWc0bHIxZkFsai9m
            QVhDMUFDOElubWpxU0Vzc0libnJXeDAKLS0tIEdCdUQ1bkZyODlpcWc1U2FEN0FP
            WEJjS1d5WmlDd3pGMnJvc0pmMTlFRVUKTuOempzHyo/jaNoPskhEUQCPD+9hC/RQ
            iKcjtCGyEe+PhqNx77tCdNWWtatc11y6dBR4DVPyVSMWm8fyFr4mcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T18:22:14Z"
    mac: ENC[AES256_GCM,data:KUExuI9AJwl15DCWvVKgi8NMCCQiFlk8b1rKvBf6Zi8468G8yOz4SRu12blLd1j0VoaOnYONiUZKDRxkz6wC3IiDJYXrGy9R8k4Y3sMjpNhG3DTGPV+pyvOeXX8Dagpc9JKq11VBdv9y547ferfLsJooiZba0bcDb8hV0G6BSBY=,iv:Inz0ASGsS/RrO3CZs739xhhBEo2vtNpE5IGk4DQryHw=,tag:YqdNL3pwCx868BZXHMJ9QQ==,type:str]
    pgp:
        - created_at: "2025-12-31T18:22:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAZQhWFDDp0dIEI9dBWyyJyoyupU4LJJADGxsNpBf5Zj4w
            yvQ45Q4hfe9Zws1um+rzuZm7gjFCu37zcnFWuLJY2f+EnwrS7UrU0PX6wYeOdcer
            1GYBCQIQsaYweFzprubhnmWv9gIcM0B15om/QO2nKcuUABy/k/TfEh2zFwnr7mAG
            PkK5R7wcgWK/EbHigpByGot6m37FjOzonMeKqvuk4/dAr5GCfgBsdq6nV/F8SXbz
            cMRR0WZF+xw=
            =3UTo
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
