apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: vpn
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:rG/xqXPqQmGv,iv:4ffRbxqdfcJbEOxJZigMfMWAQIG3GjvI19sg9iKcRrI=,tag:DauJ1OhKVpkvpQqJWM3svw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:J0f8I9wY,iv:ffTFL0sYTj9r0ncg2tiglKK2RE0IJPNMvE9t7aJb05E=,tag:TygzmTZH+shjtMmCV7DKZA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:HhpwBWzvh269zuZEEYSoHgnlABHrW8FYF2eLM3fhKbb1qZQTfi8rBdzoBks=,iv:yG33GoLq5VSFoXTMBOHYPer2qFdZ8/ujoFV3aYEiEhw=,tag:Jl99+QXTnrJCoJL0YxDkkQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:4k4BdX+QFk6wUdY1fP+V/A==,iv:wOfTf2fW+l650pW3Guc10jYOsJnAmAYM8zg89FEI+gw=,tag:Vtw/+/rDWbqpidN5CFkVhQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:wi9MD2MNWA1GrqzLbkIbLgxCITuUV/101Px1wLwabaT+lIz2Sm2SVPKC9q8=,iv:QBbkGqkq8GOwXVTuxjZtFTLvbx6VGEhbVNsqc7eXHRA=,tag:IXc4dG4kHYhlCi9zYrdeDQ==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eVUwZmNxUUFBWGFQaTVl
            enM2WmxuazVmMUNFMTVFYUJvMlUrS041eXdvCkJpVjhKWEtaWDNjSW5zSnBhN0hZ
            L1lvZVRjUTE3ZzNkSTNEUjd6T0s2a00KLS0tIDBCYUtPZmwwVkRmNVhyT1VETXNq
            N0lLNWZUTVJUZ0p6Q2JQZUZXcVJYbEkKlOVQBLSI+iy+p9vQcb7Npwq5CzVGLAOB
            jNpb6NFoS5MevQarbbzAiPjfb8+gq6o4WKDVzaPy02SKnlHv6kGxCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T15:20:26Z"
    mac: ENC[AES256_GCM,data:OdQKZ31K9D/FFNRc5EwukA8USIAhlU9+IM0YcOpNeQR5sXEH/Tr1aibQeY7PTEbhgSojsURW70mmPJsjZlOLF1vf3CTyCKVM0T1uNJsYT2YbhRSGPEATK/j0o+MUYU+usR9Lkx4h2GBQYh5UTs4iEWS+GoRJ2/j4SCvzKpbB4xQ=,iv:k5nJ1e/jVWa4fGqk52ge1chj9xntyMG49EfD/4YhU38=,tag:7YzI0k0boitygt2bHthXMA==,type:str]
    pgp:
        - created_at: "2026-01-09T15:20:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA96A2M3mLP9BiOlRpKp3GOibrinL1jV7whS+K42J0WmQw
            NR+Ia3TjA6JayMBBR043dWenxSaOq2xt0JdNKAUK7FZNF9IWfXei7SFPE+Tb9p0z
            1GYBCQIQVCqZYiL30FJAoeb9MED7PhYkJnScBOz3+CKahKnxk1KC1xMFFiF2vMrV
            YEqwo9NgnpPdBf32IumrcmHgb5CArbgbJ67QKsrOuYiY9iDLkdsfxARhll03W8fX
            T+Xc0Fbl1HY=
            =MTib
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
