apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
  namespace: vpn
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: cilium
  hostnames:
    - qbittorrent.cluster.nelsondane.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: qbittorrent
          port: 8080
