apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: speedtest-tracker
  namespace: monitoring
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: cilium
  hostnames:
    - speedtest.cluster.nelsondane.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: speedtest-tracker
          port: 80
