apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker-app-key
    namespace: monitoring
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    app-key: ENC[AES256_GCM,data:yY2O24EXVQiile2j9E7+JkyT4iD/l4knikSZjy4Inl7UTrQDBWIAf7P9e1gkRhYOtcWc,iv:fnoj7EkdSG0p4vyjvdszqubiwLlk5Yf7eKZXY4tCmwE=,tag:xRypXOkBqt+Co7kP7ymz1g==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM0NKbkZZZHdEK0NONXFm
            UEoxWGN1TjNzY3phekVYMDNJUEpaYlFGL0hBClNvTWVIRDJDakV1VkhPV3NMbVNB
            dlkxbGxSYkpNd3JyM2J1cEZOZElIRmMKLS0tIHZpbmJ6N2d6U0JnYVdXUTR3bVky
            TmR5S2JpLzJVbE4wL0w2VnIvd1RPZjAKVkujpLOnYQbEJIumn9FnITQsIaganp1J
            RoR2drauCA+aoiVE8QrgZGgYcrlhnWii7eN06cHW1Nik0tK8kVsQqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:25:56Z"
    mac: ENC[AES256_GCM,data:zIpzfWvWyQWw8D4btQyg0H0o7sNyA3uSAjNx21FIkeYI2KBT0OEVbLZ+XbwQXQ0T5IE4P7CpaAvqLRSj77KLtzqkVcEuV7syZvxQr+LLb+5ddt+hdbVmZNZCn2A6P6OjCd361ZjQYp9YY4TQrBIFQAJDeWbeYVXbs7dGlheGHM8=,iv:ax++X1UR9cZjt8R58uXkvWPAKyp1h5tT9V/BQE+FqMs=,tag:b26BEgApY80cP3XGuSdzQQ==,type:str]
    pgp:
        - created_at: "2026-01-05T00:25:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAodLZisqeGIqVuwhpEtCnkqBB8F3PW3RnFWwEja/mhnIw
            PeftlnlV1NvFaV5GeF90yPXn1Ulm8b+wasnnqtrCqEVjj/oXRSZuFOt+241f4G3j
            1GYBCQIQsUeWlvPFQTBNFMFrmH0Qa35ID+qXHjUckQtNXiedLcNBzB9YQOJp2Db5
            3Ci1Vs5+iI/cItIInUiBe3ieoGPQMoR5DqaGCo7JnMm+38eVNZ/NwJ8egcpp+GCi
            OYNVBAz0V2g=
            =Xys8
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
