apiVersion: v1
kind: ConfigMap
metadata:
    name: speedtest-config
    namespace: monitoring
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
data:
    APP_KEY: ENC[AES256_GCM,data:+uHs93qgdJpZ4HuvPXkxPmX1StLlOXOttMqRZL2dw8kL7yioCy3MqJ6jlzIZIgfe45B3,iv:/akoW8P63R0E8EBbm/Yh/HNd3yTPCgN85BjkKk28WiQ=,tag:Kb73qpsLAN78QXJA4c7H5w==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbEI0Sno0a0FDSjdJWmNQ
            a3BsTzB2QkpMMjh2R2NOQS9CNXcxcVh1VW1jCjk0Uk5sNHY2ajhJQXF4aHdteklX
            a1l1cW9sOXNHcHlSb2xoQkxraEJOSEkKLS0tIDVCSm51YmFuRUJjRjNsR0o5MVFh
            c3VjN0JLbVcwL1dhQWZDcGR4VEZoRFEKVLr5kTs+pGwyMiYMnNkr8Faa6nKVOIr0
            Es7wfWQq4k8NAxkuoTKnZ8MVUpyfxVuyaOFhgZRmz2rj0zhFDgnzJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T17:01:48Z"
    mac: ENC[AES256_GCM,data:QHUrZCyCtYlH4cQtMTvjpEi9vU64GXdp89j7v2YRK2EVY0MtRzqcNwuxGox/Zuw0/J1TB/nQddUytMfvA6bVQmQGuCXiG5j+lg6cndUP3zyPJ6GToVAh7mbYWyJl/pbzMgrf2viiGrnhoPr1FrVZ0wY40qdJgQJuM2d7ZepXSg0=,iv:7DkhemXW4T82aGAPaTcXpw2TdRzLuepk24cyAnynRL8=,tag:VAVabzE6oioZilcpugxFKg==,type:str]
    pgp:
        - created_at: "2026-02-13T17:01:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAQbBufswQjrxaLGklOcUuCQ2+VkW1XwMWXO8F6kz9yScw
            8DftJE2aRYG3Ol2USFOnpJL3Joi8V2yuWSfFvRClqbX5hFVYxQ3DK37GXMdJn1NM
            1GgBCQIQnFvzNIBeSdYrtOEVIWlcm87nJwbdAX3QKRCnaZxjalCJAOoaYG9RroSq
            1usSXylyIiPyW2/QpVbsG3h6kddaVAaDnZPpzfmstTKpLwKGRZYRPfIWlSZAKZ+D
            YqdqdSvqRsWSjg==
            =BIvD
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
