apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker-app-key
    namespace: monitoring
type: Opaque
stringData:
    app-key: ENC[AES256_GCM,data:NHyPkl+7eNA/ThvhI0gwIj3MTbhblBvYsymat2+MIQ543ZkJNFyy0AcUKK+qC5omKSjH,iv:VCN8v/L0/b2KQGU/BjC1YLK5o9NvUG4VzeRhDw0WcpE=,tag:/gjUtWbEGWrChjBZsOs1aA==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnei9JbDY1dGdTdS90V3BY
            ZVBDT0hqOEY2Q29DWExkdm4zTUN1cWJrMkYwCkZ2L1ZCQzd3cU5yNCt6Q3Q3Z0F0
            aUFvdXJpVzNQTExKMW9FRnRRbkhyencKLS0tIFlZS2s3c2EwNlh5MUljZWhCMExU
            K256UXpGdmQxUHozVGpGaExaQzBDOEUK63RliSHLc6vACKw/BGNHBsBOR4K9utdO
            t+1arpLXCZdtRhqFaqGBS7gtpM/X0H36O6oz8OU3cWMA6p55ZNtyRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T19:57:28Z"
    mac: ENC[AES256_GCM,data:iQpv9Dlt1MdUVOD8NwTZN6aK9u3krJG64dhVdb8kWUn8B96juTv8KLlsIqGFhrJ1k8Mm9gQySjmSWszCkv5T4Yar81VyfahiXHryp78IWQGX8i7wzERFbO3AGaEn7GLlfzwHJbc2sw17ssd8VODBgWjTWv0utIZjsWpx3sySDY8=,iv:2uU2vg0/w6x+yyv8Sxxw6q4TYSBfYMg7tsKD8d7sykA=,tag:Tjr0lKaPVOQTXoZ58e9vtQ==,type:str]
    pgp:
        - created_at: "2025-12-28T19:57:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA6sUb/Wy3RZjou779hxqwCwssFrs4I9hdvIsunBGFWXcw
            1idkDELIbT115pX5pxd0rgXvUqGkGd7Aixf5SqiIi5QlW5vR3zROlbCchSv5fL2s
            1GgBCQIQKl80SFcX/s7m9Jx27e0g3jJUsa6RQN9F/PC9UH3sFOZGP2aWLl6ccmfP
            ZTptAqNAtIlmQvV7U0kD0pbvrxNIZ9Mlonqao3dM1nyvSjWn8zxz6MLLKDFcpEUw
            8iANxfa3jCjupA==
            =hMWv
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
