apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
  namespace: monitoring
spec:
  selector:
    app: speedtest-tracker
  ports:
    - name: speedtest-tracker
      port: 80
      protocol: TCP
