apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pangolin
  namespace: newt
spec:
  interval: 5m
  chart:
    spec:
      chart: newt
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: newt
      version: 1.1.0
  values:
    newtInstances:
      - name: main
        enabled: true
        service:
          type: ClusterIP
        auth:
          existingSecretName: pangolin-secrets
          keys:
            endpointKey: PANGOLIN_ENDPOINT
            idKey: NEWT_ID
            secretKey: NEWT_SECRET
