apiVersion: v1
kind: Secret
metadata:
    name: pangolin-secrets
    namespace: newt
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:ubFpw6c5HCcaZIldXN1HW5EPMdRb52apITT2nWGrvQ==,iv:d6fMMK1JYHPqOmmonoJwWRnlwB+E2ruBid4fhGnPeiU=,tag:4tKfWb6MyjnvqXkXrXNFRg==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:5llZq6eW17dCBdnIsw8t,iv:6po47gvXNYqrrexQvF4vy2Z2+fzzrmYIosE63jvAoOE=,tag:QN+xBWIaGzx1h+N1+TukLw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:d907v7xizSPe6RaGt0VJokjf9P7eemnWzaBINqE9/QkUgvpRVCbMmwgM6TYnNwZp,iv:NPxKPhnYNRI/WbuiG3xjk9TSZHR+mklmKTrdhVOghPw=,tag:o9kZxMLL47jS4pQqZ+GVQQ==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWnZsckJnY1F6MFVxaEtC
            K0tGQlQvQ3FDa3lPT0YxOGp5SVpiV2FPL1E4ClBERGFjM3lPZHNUVmxYcjlnV29u
            U1huR3NXVlUvN3FXMCtaZlh0U3RBcmcKLS0tIHJPcVBUeFdiWm93Um9OR2NOTVQv
            RUxwTEJlSDF3RlAzMGNHOXptYXVsVzgKC/S00FvTcuXj6X9t6/H8l7GMsYAKNWH8
            AsPqkoZSu7Hcx1wzgtt5e7cywOTvHPHit7M4rbslDWHKG1pa3gjhvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T16:49:31Z"
    mac: ENC[AES256_GCM,data:L2GsAX1ZjH7EqWl64vX+PpaCGOA253dQGI67jJasYMA8h646VAd5dakwbT+7RyMVzWTnLNe8mFQmlsA94zsPxwZRm+Yk6f7kPfM3GMZBc7d82T4YGooKKh3bSXbY633prqgk4GeA4eLp+s542Zzn5kAPzWQjzQOlsk1iXqKCxzU=,iv:3fo1LzL5V8KAoaRjI3yoRiQFvFV6+rx2U1Yj/7ou1+4=,tag:rlF2zFsoZgvfi+WW2yC8CA==,type:str]
    pgp:
        - created_at: "2025-11-09T16:49:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAzZTOLVNAeyVGDmxRiARxtR+tRrtsZWw/LqEy2Sr6hiow
            TiDkIylnbG/QIGjlk6FNY6TT4aUV4BHt/nzn3Pt/OPFBVn7OckG3cvCLsG2A/gR6
            1GgBCQIQCXSLhmSCDM0nQYNxn9y5TX98U7kNRMb1POaFoUNFf01GICRYJlVY+w/D
            kU5kRrhw21wkrD2JFQda3i1TBPZU4l9/sAiBRe4df8zhEFb1GRKfGZg0VyOoFtmr
            MRD3iLCpXPSDcA==
            =mKJu
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
