apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./capacitor-next
  - ./cert-manager
  - ./cilium
  - ./frp
  - ./gpu-resource-driver
  - ./longhorn
  - ./monitoring
  - ./nfd
  - ./reflector
  - ./renovate
  - ./tuppr
