apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cleanuparr
  namespace: media
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: cilium
  hostnames:
    - cleanuparr.cluster.nelsondane.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: cleanuparr
          port: 11011
