apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cleanuparr
  namespace: media
spec:
  serviceName: cleanuparr
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cleanuparr
  template:
    metadata:
      labels:
        app: cleanuparr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Always
      containers:
        - name: cleanuparr
          image: ghcr.io/cleanuparr/cleanuparr:latest@sha256:386d51d84749f41060ebe99fe3ba34772692a99c839eee19899653dd69d4fa37
          command: ["./Cleanuparr"]
          workingDir: /app
          ports:
            - containerPort: 11011
          env:
            - name: TZ
              value: "America/New_York"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: cleanuparr-config
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /health
              port: 11011
          readinessProbe:
            httpGet:
              path: /health
              port: 11011
  volumeClaimTemplates:
    - metadata:
        name: cleanuparr-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        storageClassName: longhorn
