apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: files
  namespace: apps
  labels:
    app: files
spec:
  serviceName: files
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: files
  template:
    metadata:
      labels:
        app: files
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Always
      containers:
        - name: filestash
          image: machines/filestash:latest@sha256:41b0626e96359a9712a5afdbb2a3a3c83f47656faa6fb5c84e83e9d4ee40b5a6
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: filestash-config
              mountPath: /app/data/state
            - name: media
              mountPath: /media
          ports:
            - containerPort: 8334
          livenessProbe:
            tcpSocket:
              port: 8334
          readinessProbe:
            tcpSocket:
              port: 8334
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-apps
  volumeClaimTemplates:
    - metadata:
        name: filestash-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
