apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:j9xgfpQ0,iv:qYg9zTyaG5+c10h+IM2PNNZxk2n1zmah7wYtIrWYJX8=,tag:PRW7fg02OiMSRoOsY2j3rQ==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:jWJeeA==,iv:2n0Llp5O/lNyu+lqptDldq936Eor2a/XpfVtXcctqVQ=,tag:2F6hNR3C0uvT5amUeLVvKw==,type:str]
    RENOVATE_CONFIG_FILE: ENC[AES256_GCM,data:/Sepvzbz6UVOk4fd9G7mysz0TSpN68RHKQ==,iv:6dbawTQEItHd5ulkbH0+W23pUlzVz1/pTfpoEKIpgJo=,tag:PL3vCkD3xdWlG9NEoHrUrQ==,type:str]
    RENOVATE_BASE_DIR: ENC[AES256_GCM,data:i3k9L3nacWq6w3V85nM=,iv:jj0bQ+Bztxl6N1N1cMRtan35IsGmj3eWGNiCe6y+B7s=,tag:gFQC002aXoCyQGfvdmR3UQ==,type:str]
    #ENC[AES256_GCM,data:DPETxyf4dR7yuEwuSxs89RyEB4k9RVbNGY8JIvHwdmVBlldc5gEnzEk=,iv:+CqZCkmGJEKxpo4C5en38JzuqEfk5OH6q4u3fpu/wuU=,tag:5eU1NUWKGrcQdHmI9ILVEA==,type:comment]
    CLIENT_ID: ENC[AES256_GCM,data:skW6H4o1zw==,iv:5iPKXL/Q5sYqloJ6kDmahFbvxCX/xcuegaYV10DtovY=,tag:WPbbp0SbndxXsq7EHD9/vA==,type:str]
    INSTALL_ID: ENC[AES256_GCM,data:CFOrSwLySUQ=,iv:F/s8mhTeXGTU+W4XUJbLqfJyYBTnj3pZXMsy2iMEDiM=,tag:1o7Fyv6EgbohvcIUYdsxtA==,type:str]
    PRIVATE_KEY: ENC[AES256_GCM,data:CRHXT8vWJItLLJRPWnJ3k2qbz9u0UBGgz06KYSqyz0N/Fr7VMkHcvW/1PTzGp09XzeX9vyfC4f3jp7rlIPF3cTOiJAEoMWETNJjYawo8+wfv3+7BTBvmvZrvmCQdZYBtCFn6XZIcZJ0uRtNAnXJwSYXlDuDN8OdBCMKgRwjKEuv/UgvisFZS93E378xK1qWKncQKOUkqAEEFz0z73E82NLsGVrBfjFZ96U7SnbUTlCt6m1i9QEJx1Un3P8+cl5nGDhqSf5oqgJrGMbptPZafOxyUsrnVdCaEmqEyvp8U0EEuFn5i/sASYjThrwObTmidWdIhIGSAGp7jJByWXzd55jKub2B3uWAIACx1r/Gtso1kGWpEN0/NMEg3Z5JAhqlvmncuhA0YPP5zI+RttmcUZjtg+0PgiKmQBzsWK7bcFogWgCDL+6fhZqUxNh7xdQ6K3IRuGC4r00s5vSRMHISEqUgQxdsJATjxTsN6N4ZCfbioiVIyeYEhcFkEXCMv+57auiSYC0sYgAGzm9voB9c8WJt/985B8ptqGJjBzXsJVvPHlnt+OVscJVEdQvsY0deje/GAcZdkaqG3JbW3110X7m7fOzZBytD/OYvLtKZ9PegSPiciP8aFgkyrc/th6loOk3+k8JOMMnGY/i++m3XtXEF1FH/4xp9sZl5YvmeKVjT7Skh9hJnFzcPTI1mDcfRW8+NGmNjxIyXhf8ubsRbIFBwD2B7Zff5IW1Oytrboi3ufz0KyHht+30GeaEUM3FNlDJvoS1Gq9PR7Wgy+GERcDE4Mud3z6o1jOhP1yIW29mPRutMA3BDDfoK/f4mept/NCLkxeAkFuMqAWCxggKbFZNp3YBO8pIVlTShPKtZ1O1GsZ7HfdFS4QuVA298RvGDGeTVBiBxhjVn/HE/5GClsBTASdfuLzxRWLbBk1FfoBFVYKx1GUO6VckdCEaxE0AvVd7Jm5E1w7RSffqMPNrD+Y86c7B5ef+LoDKQ7G1OCoEGQGPQEVr/8BWLJvdg7J/CuXz2JXbIScwAGU0timK3z1sTrDlsPlbti0QModbAQ0lI4gfHQumBzLwNZosabfPgexFCodZBIzFFV87gbwgKWnnII0KyIvUsB3HQPp3eWJYtMqd375NEP8FlXS9eVJQ9rqc4iMmc30SKkiYVeiEhnVbrGQbiHE4qHgP6mbm4QPFRGTzUL2l4mOo5OwBMpJCNbJBm8hgBp6gV6+2c72BVGZDKW0ufQBgqfGTE3WT3DI6x5XGbbCiEvyT0mNOaz85fwwLUlqa0KG3gjtIuoEHI8+f+GwV3fCV9ixo+o30D9ZxTE19Ykb4F/5gdZ0XlYfQtk2rFgWjIziKGCH1mZ7qUHyDsj/p5XM82ORt26DFCrOQyclgwCWnSaOGlrway+b0jKFbg0jtGGsPeeGgfMRIuO+vAFtYsmfpN51AvG7wsobqDP4W00isSMI/Iux760w8JMmBJ0/jB29FqGK9wZnTR4WPA60cb9fFrgWMrBGsCCzqAHQyYly46B4jPaiPvIuKXpPWxGnXR7IJCua64S/7YOZG3KQ6NEhPN8bMUeNvtWdzTX21zJE1SDI3+SWsZeaCPB01bzvGVtkNic4Amph7PVms2mE8REJiA0i8PlGG7QrlOx+OcXFCmETLIntZTT4A956UKbtT7AkTki5GQFKmXi6J1OsDopxGXl5K3oZECQn0Xu8mo04KxgBsMAhKHFexGEUwpc6TlchxPTSsu2OZqtW3hqQXYeaYmDx+ahudD/itRNzIZwna9YVaIZDYVo4nQCRaA6kt+QRZCuDjvhJ5Vj6inEmNbfDPvWZivkjw/CSDSbNUBhkWT4Ijs8A3QQO+bid2irPkdoAgpPEMxQ7+VN6AsHtB8uVHwhru7J5cEpL5nkmB5ZerRYfphPiGMK4txr5Ohad2CxYnSKyU0SZV898CoykA8ngBLRGbVji+KyisAJkL10MCqHgekqS9fdL9R3ma7/M1I2cYNy0X3aiWz8IWEFP16Hfldg/glV+OW6ih++8avmHBFuO87ABJ+7kP3GVio8DHrsKZS+xulQLzw2X5aT1K0eoBoMWJNrLsIuQck4rtb5Oaz+nXl/A8GAK8d+W022Viwhg+Bp+6JP/0zy1uSqP3pin4So7dT3zKpocrjx/AS3iXw71/W6VUiPlMPsA2eb2nU5QVPE/xy2v35oSIc8jLgGzAIbrWHVz5al2WNRNoYFtXr0ZAZOwg==,iv:i0wnkXxoZJBKJQaqjvXdyA+mgG9JDgHukb7pXdJ+IYw=,tag:Kv8vVDuCuNhX8W7olIRrug==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbHJ2ZWEzUlVtQUNVazVl
            dm1KUGRHdTN4dkp6eW1OZHlLQ2MzL21Ua0JVCmM2QW14cjdnYmcwaUx1ejR5UHNt
            SytYYlBTZkpIVVNrV2J3Z1VUZkN0Z0UKLS0tIE5SRlVpTE9BMnd5b2FsNzRkWUpB
            TGpKTXJUN1FXWVlrSGZkTUFRYkcxenMK6k1AiyQSkvcIn1wcZWY+6D1+5yfB25m5
            4HQK5Rtvg8YVo1K91XkeDdjEHV+m6qSlZ7/x92OJKrENnqKBcyQ9EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:12:54Z"
    mac: ENC[AES256_GCM,data:SSVOmWbUQxBmE8Q+yF+FHVRM3Q+fwTsCOhjG9CuEs2qFhi64VSn/MT1xM7gE18mDpjoUp36kgisVYwA7ogYQXNpQlPNHNUO7a9CAPPDLHxZ/hSXmeQtzF6jBzoq+p6tfax/Q4K3rw2sGTiMKCgfN5mmH2LPPQwZsJnuPqajzOVw=,iv:Xg7rU+DCV4cB7ItiF9Qwez9TG7GyMX+9CIplWA9kJvY=,tag:0YFBb33U9f3IPuJuhV/aEg==,type:str]
    pgp:
        - created_at: "2026-01-05T00:12:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA+eG+vbnvEqS8CRz75UZB0RcI848wmbyilyCqGEdo6Sgw
            UvANZ9Agbxi/1Rw0Y4N86yi1KAR3vdpxhVuL/D/UAiT5QnoU0dO9xBIz4fhO/vsc
            1GgBCQIQMjybw9bPXBDx3Qj68PKfW/EZ56tI8dktguuGIQ+PIV1ftR9Iyv2HcPk/
            IySONoHrBnv3ruJJJxMsN11FA57Bk+4zKvRTy3s1Vodes+NztnXggFNluV53FXOe
            NJQwh/oDP+UJAQ==
            =tKYf
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
