apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:GKW3j689,iv:4FJy3ZZXxYhPa7a+T3GoBUhH1hTt8i1bCkxZ7MEN/vs=,tag:WtC+tpFzh5aI/O/GFXecpA==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:yJzpYQ==,iv:/GS/472QcqtkjR3qD3YjSNcQ1mv8AvUmM2U48orRfeI=,tag:qslFhfnGvTJvdEGDPdBZMQ==,type:str]
    RENOVATE_CONFIG_FILE: ENC[AES256_GCM,data:N88llBz5TMYRzV4aYVKKEhjTDXMZeKJe8g==,iv:fdCKtRlh1pt6F+mU1c/NQzV44jUvb5oK+Ier+1nS6SY=,tag:4FDeg/4N5PilDmjtpRYhHw==,type:str]
    RENOVATE_BASE_DIR: ENC[AES256_GCM,data:pn2ZiT5J2bKADRAz5+o=,iv:eIbenRKKJm3zh1jct7HxWF9ZXpRvlZsiYB6hNu4kBXw=,tag:jsdV5jsemGh/3Xy/F4Nycw==,type:str]
    #ENC[AES256_GCM,data:mpS1RfVfERD1/Z8PQ1DYHRVIrcu9BMYNPURtAWKSTm+t9HKkH+QM5mHNZa95/4ge29hmPog5sTC+dwRhxjBr,iv:kKaPPBFWu8SQh19nCLOSkQ4f8EZzX/jO4NeEHqYmZWg=,tag:SuzW3ShE6Ps66477ZNRmmQ==,type:comment]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:4xaJMMeZMJqTf0a4lzVrUDEJLLgeexElYAIHeXWwzjMSHrJd6gniWg==,iv:186z+XtiQrL1uZm7Z/agZXJsJDSnUu56rhQkp5rD3dk=,tag:KOcLAe+4Kq708Emut5XprQ==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:vyRX74CLcw==,iv:MNUAkmQisc/uK/0RIsftFFQEKQ39tnO3tm9uCCdnBg8=,tag:ZLLHw8mimdLtADmsT/V91w==,type:str]
    INSTALL_ID: ENC[AES256_GCM,data:TpssFi6ZU94=,iv:kP3TAFVhsYxIzDoCSbpX5voFdM9B2TzwrN2nUfzfDEM=,tag:whPj4Fw39tQDsNU4m1xd/g==,type:str]
    PRIVATE_KEY: ENC[AES256_GCM,data:XTSuE+HhAiyWnOSC5X0V69BiXinDN/ruTy2pIn+ehNRYS4zO2t0zRpbW95BTYZsQFSQ5NotsKT9/YzO5Af0vunBDX6xUSnj9NHeFopfmWB6Tm4qfAOA49KkL4ifYyME+2oIfYDxKQQUMI5Ks/Yv38mclFaYhJp3Yd8RCbA5V36EQg8iWRgHJW2CKsyggBeTf/ZaCMVNXqk8KVPejXRXZMLDVcrNyuUCtU7CtpcuHfVbXWDhJAGKvuDQKaFsvgeOgw/j6+AqB4GszY8I1484qoKua956o2vfRAeUJ9SvPJkLJMzOw32XY/48FlcA8Cu5CUFb9qyVWEo0azDo4iiwcNB5E/0V0mobaEeR9eadJ7WypGmdwYv4ezQZptq2OYFAHj7jeQYc4lZHwjD7I/JK+6GdM3bm9/tcgohenfLnT3PZDr7/ZEX47eF8GxMHtrhpGQsMXEEbOFb1PlgI8t4xKK0YbZMG+Ma1HDiXIkAh+/w2HFlocPfzh8DRyayAUEYGZgwDxCE+oxKbcKcj7S15xQBCS5eTqmmjlh/3fq62dWre9cUZG9T4SNVJ95afN84Hiuj+kbwc4IQiBTeYD6/S4IxUpxjWOGmwrqqMFBL4Njh/yIQZVlCvxziKgqO0tOQwkPf3WcOaHEnx9oSzLp7MsQqefkLPC/X0z7Fy6VRvipOmW6Ms8XXsFt1cXu/W3cAUBfkBIOiLr+k//w0MP3/JgsbGFd8lqr8xaVSXWNNCqDkY6vwiU1Fj5M0ixQxTtDPo3AkBAg1ccGADEsdPnzIeZd8A+AhRa0RuKuGOqSbxAi7SNubtNgEiMEw+TIVTOv0qhrSTgGAotfAKB2T0zYU1EpU5mY7b826PF+OhrtUvz3vThjsgxq84RAVhFkn4K8uyLkxkFAwNXBB6hhttf6zNqsSiIsdT7fH09VgqpinaPNvdxWTQ5ULHsXnVX3JlH70lt8jKyy0Bwl31TlzkR2q3rIFC6Tzq3I80S3SjmvFU6bwt3O35kbHRDMHrfThBgvUHtkFGvpA16gqsbzGXajDJjUpM0qXieuUzK9R2GuSDKnOWQaVSwdUnMh83qOicc96OYdk/fD8VVPfM1YmhGsRkeEHtPBnBnvUginSgQxUC6jdEQ2QowlQwGHeWTn/37CLyHKXLY+Yrw+jPoGmqcxgCWAQhS9LTARMgvlDweCnOlr2uxjuF0u8p91VJBH6DQzgIdsQg9vMRf33AnLTrYfE3wg/QTCQMaA6euRpX7TqoCnAws4jJ38r564c05CjH32IHBzc5pO0LzuaMyhlU4/vTTHlCvAUxMXVtCR4umnRndlRx18i4Fg1P+dRRoCzYiF0ajZ7Lt1d9jzNlTN80NA6yYjHNmmYYa7VsV8ONvqHz/3TyXceF32DPiTdzTC/GD6n6nto/Mf495yyL6lzpW1+oyR/NPzysP40I4SiGFzdweCde4wSB7VsekptcRdq/f1G/OWqQC9vsVwUuGfQO2ikQBKoe9fxQTVQvgfduI+jK2PyrZv8Pr7DYTMIo6dLvfubU1a1rNgYiOcnEVszJ+I2pcZEaCj11xLhlR/mHnBfKf/PAGyRt91XvKUJtFGzkYqZtrX/BujIXIEfiquEpOtLnfypWaZsPVznreSAHfYavCYOND8lxMqb71z4DdAj0GvWZcaO5KylTJm64lSkGdivoZJTLoG4ILIacuFAZOr8nm4R5fe5DCyyEmSmnhkRxBUv8hNsXQjdAsxjw8rW+bLj09jCcoh0Tbhrospx/U2ngPVPsjTOAn2WX8GyJS/rUqn5zIBYaKzkfbF4KojLQwDdxz2YDQAykeImH2PqG7H/XdyKq7fD2To3i/zrlkF2XSXCGoJliD94J/P35pj+6mVU6qTFybVWcu0+34wXZ6nRXEPDknKBjda5q8OujSs3G4jF2A6VQJEBXc/Q/E+CucnENbAEazNCAGmJyUfTxr/S2ewoCZwzst+zAyqBfdHNmMOb2sD3/fhswjFT6n9qe6iRZ8hVBwJlDUD6leVourZojbk2GkzpG3V2Al61BxUyAiu0TYnM+bZQveYPpz+l+WIdFmA7gUmMGEAURDkQBgBaEURP+my88bRfSGIxD/MngawW+22Qyx4scoiDHKwWLJeqJ7lynXqBvcubejC5Xz0eFJvEm68cWdNTwR23Gk4Drc4Thanl0mCvvx0B68bYY+O06hwKryBBzcYEh3s6cVBqEmrEVg0PJTVVsxjxqRTQ==,iv:j+gJRXsXtitbEdnl/N3riFG/NSvJ2ywVBkgs4bFKfow=,tag:485ovpotTN1QNqvXAmr45A==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eEU3b3FKc01BYjNQL0R6
            Vm5aVTJQWTB1M3VidnUzcndrTWFKSXdjMkU0CmVMVU5vY1NiSnF0Q0x6cFBTNjNX
            SWszNGUwM0EvNUJOQU1KZkhVM0w4RW8KLS0tIDNJKy81d3VaWHZWTWJRLzlBS3g2
            L1YwL3FKM2Uyb1BhN21yNUNzN3BPYjgK6scwdxksSwM9fLVlK+mIxyihsRleP6qN
            ky8fHtMxwh7BHdjtSW4GKJd73YcNcJwzY/uWGS31I5DwbaDZ7B9lOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:24:39Z"
    mac: ENC[AES256_GCM,data:iINl40vKvovrTVRumoUn8aKui8bp1I72zdWylip/njCFhXYV0vbq13pJguHqs/nnYw7uHY2uSQyQytRxMijHhXzAGv2b8zEViP6ftA0gJcpzJF6J/dmJYZ32w+YzuZ9YTSqb0pQz1oU9e6MVSxlj0J3dUgJJW5wSVj2QB0VP7pc=,iv:cmI4RBXERDOS1NG1xIznja6LH+6PPk0sHitD+MrhDUU=,tag:3GYLJDMXh0FnOC3IGMTFFQ==,type:str]
    pgp:
        - created_at: "2026-01-25T18:24:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAR9kIt3fiVvF2P+lxw36ErQW7Y9S29cv3badNbMNZWSsw
            QCYqeYv0KFgtyTaabRgbfhNv6U59wxVw30pD5+GTwPKhK5zOfOmzIMmEOXsRFk3P
            1GYBCQIQbom8aTF289ODrFGqb8UxLsrcmKUrW/ezy/X9+YNlt3gwaYRmOAObfKOj
            F5VYdhX8sgKjIEtvuh01TE9E7O06RuOuMRaHU/XtF+/LJ86gD3sS4fBzEmHRxC9F
            5Ddoid2sHKg=
            =6cc9
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
