apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux
  - gotk-components.yaml
  - gotk-sync.yaml
  - gpg-secret.yaml
  # Infra
  - infra.yaml
  # Apps
  - apps.yaml
  # Media
  - media.yaml
