apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:rFsBEcQ=,iv:fCPe1NI5bdiJUIApz6TSW4Ry0mhh7oqlG6Mj0zRkY5w=,tag:TFnJBIx+ZrFd8KnXfIxnxg==,type:str]
    admin-password: ENC[AES256_GCM,data:Vm2KHiQBoFHi3LgACg==,iv:w1OgdhbfiK71O89RlQ8rY9AxIM8DCNAuz7EyeWI48iw=,tag:PmQSHAYI5lJFySPtzPQ7hg==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByclpLREFnUlB3amw0OEE0
            ejlmck9YVDZjMGk2Vkc5TTZRWk8zMkltUEhnCko5eDJKYndyb3BjQ0RRTFcvWUZD
            SUpZcWJLYzlaSngwQmlnclZEQlBLWEEKLS0tIHpZWThSUUhObkZaMndIcEtrUnZH
            czdnSnI0VG9jUzJqQTFJeGpJYUJUcWMKx7+MnXb6s6j+h160SD7VFNoun0bgvM3d
            oxoOKIouIH7H0QiGLAaPVMXJlbiAkfT6wgnFuoTMzYjRtZS2MR5IxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T21:13:18Z"
    mac: ENC[AES256_GCM,data:x0SxNIPKjhtyeeWBbVKhL55TmtZLNDrLYfJ2OdOnH2nVKzCDGvuUNgFdE7l+ghVQOedODXj4Wuzgz1vTpvSld8oBaM7mWs4KPA60xb3yBy4VE5FF/SU4fG7/wuproLAMGb+BnygPn+ke3adG+NaGwqd+wTKFH/gF4wW7Q5Ef2iU=,iv:ALkg+e4MhNLf0fc5plc+NFEQ9XALPbmjKdsw5kM9anU=,tag:orbE5mxsBOQBMnUuKghxbw==,type:str]
    pgp:
        - created_at: "2025-12-21T21:13:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdA61HoyGw9RlA5HR/P4A3zcGPWZZfFE4zaQTGsYF59eDYw
            JQy7Aixa0x4naJ4JW8L9+n5fIfqeGUXJRHgPNMQPoudt4NirVlDZhT6lR//pCzG4
            1GYBCQIQWFQG6cttNo69kMe/Ogk+sdvqokOKudy9vb8a3J780eVAINJ8g4khWdCx
            BIUfueQEmTTejll8f/h0Kuzr+p66Zg7hUwT2wilRyXp6vtBkEPSvzIyxa+EOzCNm
            oAQEMBiGA9Q=
            =KFo5
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
