apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
    namespace: monitoring
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:5Gsqgio=,iv:UhGruI55xgAfN+se225aX4K6L+2FXPRJjJw8L6Gjt+Q=,tag:NjLJjPHaEgZnz2cUszTGNg==,type:str]
    admin-password: ENC[AES256_GCM,data:yfLQ/ankBQHCTgYkww==,iv:hlyd8WgleosZQnA01oImwaglHr2PXHZvhqNu9T6AjhE=,tag:fUZxfcVYtZNCGuWJYR2fJw==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dmJSN3ZnbXRpV0o4Rkx2
            QUFsZHV6Ry9PSkhTSlZmMUtZenhTVDhLejBFCmN5bEdJL1F0elpvQnphc2ZEUE5B
            ZWJyWTBwek9USVdNMUdEMlN1R2I5MGcKLS0tIFRhQmQxK0F0U1B1TFhDZGgydm5O
            WmVrVGtQdjIzTjRpNGxwdnFqejY1d1EK7nkGQ+0/igLqqoarZyeuv4+BBuppvdQ9
            foM0EhVZmronf9JS0wT8yYoterotGwAdlSdTUOsBJidwSXe24jFS2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T00:26:04Z"
    mac: ENC[AES256_GCM,data:wVwi1IyQ2ftAjI/0Ls9EMoZXhermEs6PYaiYCwkpfi6clkIqc3KG9vNuSmn38h+bHbgG0CywyrPop6RcV49Jq1cgFhHMnNQt/lZXLD3Zf05Y5RUfayUfB/J3xxFGUC2tqL4H/2SpQQ4sAx4dTkEpqa9h2eWuKOJTTS9IipS8tNQ=,iv:EqHCFUmos7TqfxGoTwuz6A6jPKN/TqxDRMbUNfUgmqA=,tag:dz77gOSRsc3jAfv/uWL4vw==,type:str]
    pgp:
        - created_at: "2026-01-05T00:26:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdAe3Mb3wXxWJIkWw7iW8Ddj7GSrJEotQSP3hl5kgzN4zcw
            XRtdTllS2b6oCob4USli4Zw3Ql0bbrWQnQTkBMFWpBKvi8Trso09nHdagq9RDDDn
            1GgBCQIQm7K0kIOgliyArgeFzSTW51Mpv7nIGb1kbVqokIIIF+xM15/vBjkBHOXp
            DMeW1Ki0WWbUr7XTz5yezsikZGcOese7ao7HPd+4HD3q1yqNuXy+mOqC/zSmMDu3
            SEO95kcKMq5VXQ==
            =h1Zf
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
