apiVersion: v1
kind: Secret
metadata:
    name: sponsors-bot-config
    namespace: apps
    annotations:
        ignore-check.kube-linter.io/schema-validation: Encrypted by SOPS
type: Opaque
stringData:
    CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:GHkumvYYYT9CC3AIZefhddIe42IiVLgyzc50COeAQlZVz71YsFfbtifUytAi7CEY4HdkVucw1bDTous2lkriXQe5fglsmLCan2ON6J1sMTSC5dI5O72okkCJqyhITMgVF0NCkDbiSY4us5ltwHcdSedcR6roODYsk7WlRnEClBuydrwXD2CbCLQna8egpS/PYfnUkOM90+7efRPLXr2Dg5K+FVHaz4S25JOj6oHIm0mPHpjf53jqaA==,iv:XMd46A5lyuMDgJsF9FSuIdaVz+mHvawNE1yjKVWnFgk=,tag:TsWnbwm5c2frK8bsNfFwkQ==,type:str]
    config.yaml: ENC[AES256_GCM,data:gAJU2hA+KN/pcO2gW14mnz/jepmqQs8qamuERC2s9kdqhBgtHCXJID02bf3cxFmfIlij/elPRp4p0UQV0vNiBgvjr3zx83frtgfQWmQ1i/PA19gEaphFfJhIY7t9mnnpUUGKIQXH/q6EJPFP9QVCvKsEXwQ/0bBqaZtrcDLyCgT2yQYBnlD6B5lHh0Y1zBO5ivW0oFDywmj6OzxeCZkXTf297P+EMK5DjrEfmDTll3Ta6OWD6mcKc+LOh7LlW2+5c2kQEGxnRnBzFuJGR6UTW6nc9yJxsq05wD/gOsTEWGwjFZXhes/xx812LFPHpGkl8VSlo8ceNLc+JLJnQGbfVXP0OpdsjDqOXEF7KGxG8uhwq9Ma1sYvKcLyGriFVcwO66ntX8O2vAhBIwKwXHM0vX6iOrIKuGdLaNSyZGIXi9jhC+Nh2tZHMP1Y5xmp44lR5o5KYf7X/2HCL+5he1qf9cB6KwCU4hrUrlWnRyyLaqNsjOdc5kC6VeFAfzrtwkOgzl4SYJfqu5vq6gxM+fa8vWgTEYRKYcnHAUH39IVd33jZmRr8VObu4GY+tKoDToO4xq7m5ZH/qirtcfxJ+BK87m4vFbYe+KZrOwLsmHGMjpa1SUBQBKtBXa6Mr8PYPRJrd5goIiQY+g52it3nMJPvK3G4WcH/cnP7WLzPWm0LLTA+tUL/6fUtwhy8SOlT4dLzNCVGi+3SuzkqEPujbfbnxiL6WTyTsqUJ0yf/c3rbg+Uhs4kTiNio/8p5HUus8OikGLTWL79BEKEotfDZApRsx3Do7vsxOM8laqcff7vezByr4/1N2+vggmZAHXwKDrPZIHx41IWrvZKjXTJQDwv2Y9kf/avvP9L4PAvpKj9FDS9ocY1iySQXZ2YqPNvqf0MXEPwhSL/r2ZSCO93HqX+3iZ9LgsUeeO3HneXBNX4pe31We7k25syK6u8cQX1CpcW/GX4KAp6saPpaz+LQvwko3xKjJX0bMmjEjlba87RnEbxPv7XfNdP1cNfgADUPVPjVYpNpxeEL12eB7QVkV1Z/5+PNC3MaO/TTSSnm4JxlFasFEK0oXCaxELuo7KuGiX2ikRuqFYmEi1bHc073oVQseGg7tuYgUfxHiF9dSwGx7bmNtUws/x9sezlm48dMY4pY4L6p3zlbEjiqbNFM5rABacd8lpSNdM9x17skJiXVOXe7/K/BfY7bVW9hmoPBP+zmRYtluE+XjFaA7AhCMq5Nwd1E9iIewN2T4yLZIYtphH5y1N2y8yjsgb41qx2sZH5v7XFByFp9VHCDQq/Cz/p/v2kms8HXB77Z2O0UeubD7RwHsybLmJaBcWtnxcw6gxg2sL2ikt2dJr7MnHiZU9k/8NWmoLboBvG0XCbuot7UsJP1V8YAtC918pVZXn6pD3faZm5VIKvoSHDfmMOp64QPgJYYKO6rWp3ro0C1ty4SIdjAGP8aH0JgfZpfGdhpPqxcvE1PtWjteE5K3jGI5T8czOtyXuu+0E6YHCOLGN2zmwJTfyLtWofihOgp5kUPYvTbLsFjOq1DHHuN0SP2PMk6r5uxYnNE2bVnYxc+OONDzbRXKsrscsaqUzk24p50BQ+KtOlJd9AKGCCr/328TOtwyaBRmBbq1rpbtZapu6f4Do45pNpj2YFuts4sfNZ5/QzWi98ERN7hSGZ3dHHDaQoIVoJ58O8Kdsv64BXknuFBtDrcCp/G5eQ56/GOj7maFWq/FhRmQhYJGAKa9jObZP0OiwNHqZUhvwc0uQXaeElosKziUIDfFWynBIhcj05fmS+BYUekxmpgV7WieYIhIDBirjrzAZVDcANwOSPMMzZZq4mSdZ+AR1EqAiD7b3ihdgFppCUEFoIveMu0fLej6OP9BL0i0L5n3jFUWjGqgmw1ta57pQrZntZUGVFSNP3BGqmz,iv:g6kUR/zHhwt0gixd4jK4Wl2WydkZVsyqFH7i+VIXV/8=,tag:+JXFl76zxTmWRuiaXXmQ2Q==,type:str]
sops:
    age:
        - recipient: age1dm2uej5x6cpvclx7azp5h3ez4dp5kdggx6a30eqf0uul2deead9q2w29sf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWEJoUGV2OWtvSUtsS2Vu
            V1ZPME53VkZ2ekcxYk0xclpRVnRsS3Yza1NzClQ2NnZWcFFPdWtLcjBYZlRsOEFq
            eXF0MW1iNnAvQ2hZUEl5RnpXbEpmRlUKLS0tIGJrVzArUWZNNjlNVVRZUCtVZzFT
            Y0tLbW1Rc052TGovRGt4NFZrdUxaVFUKXN04yXH/v3l1wOP6Pe0pEhz/Ue3GfYRd
            QysUQfCRO6p4p6OezWycpqDrRfl4BjffHekMzm+YdKeBVCn9CJgxpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T18:10:11Z"
    mac: ENC[AES256_GCM,data:6EeOwaFA+Q1QJRHYY1LQ4jU3ri/nXjnvjXYZbn+MCfa6HaEyhRPL4ZIDYKoSK6pIWyKvxsXC1vj8JphrEdfAW9EPjakf+diZGriakLMXRrGfggpFygtQcSF2mKFnNpuoLRx63BZQomyap0KHtAIYpCpED9hXYgXjvcUtw9NVvGc=,iv:gGExeyZkT+vmR8loSQuyaSWW4QfyZ1SACiPESCRYF1E=,tag:UPwSAJFOXuQmeSCQxcs4yg==,type:str]
    pgp:
        - created_at: "2026-02-13T18:10:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DedmP+m+bgeISAQdABZpOwaxG9QE6GgcWSgQ7U/H8LPxADyz6MrQ7ovx1OC0w
            2gW98mXCxpkVmtUu16Dkvr8X4ycMeEo+I6Xkw4FODIUWlhvFjXqWlyMo+duODJJR
            1GYBCQIQGshfXcrGNjkrDvj3NHwPkmC/3NhceRzKR43oTSGcINZITexu20Sqx6RK
            tQ4CNgg3/6MYq60wiaxvPw2TbzhkvGjLuBZ24gmeF2HLdA5oyuZj3qk7EPaVFCBO
            B5zq9cGwmgg=
            =Bhhy
            -----END PGP MESSAGE-----
          fp: EA202DD680C3621ACE5D23171EE414C5597BC9A2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
